### ISSUE TITLE
Activities should extend AppCompatActivity and not Activity

### ISSUE THREAD

**Issue by johanols** [bitstadium/HockeySDK-Android#100]
...or at least offer both variants. Currently it is kinda hard to customize the various Hockey activities to follow the color scheme of the application. At the moment, you either have to modify the framework or define an alternative `style`. This should not have to be necessary. Especially cumbersome is it, when you want to use the new `Toolbar` throughout the application. Is this something you plan to support in the next version of the HockeySDK?

**Comment by ranterle** [comment]
Thanks for your report and suggestion.
We will not have any dependency on the compatibility libraries in the SDK as they are huge in size - especially compat-v4 which includes `ActivityCompat`.
Are there other ways you can think of that would ease your workflow in this scenario?

**Comment by johanols** [comment]
That's understandable. Then how about providing an extension library to the HockeySDK, containing only the compat versions of the activities? This could be achieved without code duplication by utilizing the delegation pattern.

**Comment by ranterle** [comment]
We'll look into options which make styling and adopting the activities more easy but also flexible soon - and definitely take this into consideration. Don't have an actual timeframe right now. For the time being you can use the methods to use your own activity or fragment through the `UpdateManagerListener` for those aspects.
Which aspects are you also looking for the most?
