### ISSUE TITLE
Changelog missing

### ISSUE THREAD

**Issue by x2on** [bitstadium/HockeySDK-Android#101]
Do you have a changelog for the Android SDK as well? On the iOS SDK every release contains a summery about the changes.

**Comment by ranterle** [comment]
Hi @x2on - we have our release notes here: http://hockeyapp.net/blog/ - I will also make sure the release notes make to the Github releases page in the future.

**Comment by ranterle** [comment]
We added this with the latest beta release, will keep doing that: https://github.com/bitstadium/HockeySDK-Android/releases

**Comment by x2on** [comment]
Thanks a lot!
