### ISSUE TITLE
update from 3.5.0 to 3.6.2

### ISSUE THREAD

**Issue by hannesa2** [bitstadium/HockeySDK-Android#103]
when I update HockeyApp

    compile 'net.hockeyapp.android:HockeySDK:3.5.0'
to

    compile 'net.hockeyapp.android:HockeySDK:3.6.2'

it runs into this error

    Warning: net.hockeyapp.android.UpdateActivity: can't find referenced method 'void requestPermissions(java.lang.String[],int)' in program class net.hockeyapp.android.UpdateActivity
    Warning: net.hockeyapp.android.UpdateFragment: can't find referenced method 'int checkSelfPermission(java.lang.String)' in library class android.app.Activity
    Warning: net.hockeyapp.android.UpdateFragment: can't find referenced method 'void requestPermissions(java.lang.String[],int)' in program class net.hockeyapp.android.UpdateFragment
    Warning: there were 2 unresolved references to program class members.
         Your input classes appear to be inconsistent.
         You may need to recompile the code.
         (http://proguard.sourceforge.net/manual/troubleshooting.html#unresolvedprogramclassmember)
    Warning: there were 1 unresolved references to library class members.
         You probably need to update the library versions.
         (http://proguard.sourceforge.net/manual/troubleshooting.html#unresolvedlibraryclassmember)
    Exception while processing task 
    java.io.IOException: Please correct the above warnings first.
	at proguard.Initializer.execute(Initializer.java:473)
	at proguard.ProGuard.initialize(ProGuard.java:233)
	at proguard.ProGuard.execute(ProGuard.java:98)
	at proguard.gradle.ProGuardTask.proguard(ProGuardTask.java:1074)
	at com.android.build.gradle.tasks.AndroidProGuardTask.doMinification(AndroidProGuardTask.java:139)
	at com.android.build.gradle.tasks.AndroidProGuardTask$1.run(AndroidProGuardTask.java:115)
	at com.android.builder.tasks.Job.runTask(Job.java:48)
	at com.android.build.gradle.tasks.SimpleWorkQueue$EmptyThreadContext.runTask(SimpleWorkQueue.java:41)
	at com.android.builder.tasks.WorkQueue.run(WorkQueue.java:227)

Any ideas ?

**Comment by ranterle** [comment]
This looks like an issue with the ProGuard configuration. How did you configure ProGuard for your build?
I'll be looking into whether we need to update our ProGuard config.

**Comment by hannesa2** [comment]
I follow http://support.hockeyapp.net/kb/client-integration-android/hockeyapp-and-proguard
and add this 

    -keep public class javax.net.ssl.**
    -keepclassmembers public class javax.net.ssl.** {
      *;
    }

    -keep public class org.apache.http.**
    -keepclassmembers public class org.apache.http.** {
      *;
    }

    -keepclassmembers class net.hockeyapp.android.UpdateFragment { 
      *;
    }

**Comment by ranterle** [comment]
Looking at the errors it seems like you need to update your `compileSdkVersion` to 23. Does this help?

**Comment by hannesa2** [comment]
With 23 I run into several other issues, is there an other way ?

**Comment by ranterle** [comment]
The 3.6 release branch is meant for compatibility with Android 6 Marshmallow and its inherent changes - runtime permissions system, dropping of httpclient. If you don't target API level 23 with your build (which it seems you don't right now) and don't need any of the new features then the best bet for you is to stay on 3.5.x for now.
I'll be looking into whether we can make 3.6 also work with older build tools versions in a future release.

**Comment by ranterle** [comment]
@hannesa2 can you try using the following ProGuard configuration and see if this resolves the issue?
```
-keep public class javax.net.ssl.**
-keepclassmembers public class javax.net.ssl.** {
  *;
}

-dontwarn net.hockeyapp.android.UpdateActivity
-dontwarn net.hockeyapp.android.UpdateFragment
```
