### ISSUE TITLE
Updated from 3.5.0 to 3.7.0-beta.2

### ISSUE THREAD

**Issue by mesutbeyaztas** [bitstadium/HockeySDK-Android#112]
I uploaded and published a new version of my app to HockeyApp (using the Jenkins plugin),sending crashes but the app didn't recognise that a new version was available. 

Usage;
```Java
    // Activity
    @Override
    protected void onPostCreate(Bundle savedInstanceState) {
        super.onPostCreate(savedInstanceState);
        checkForUpdates(this);
        checkForCrashes(this);
    }

    public void checkForUpdates(Activity activity) {
        UpdateManager.register(activity);
    }

    public void checkForCrashes(Context context) {
        CrashManager.register(context);
    }
```
```xml
    <!-- AndroidManifest.xml in application tag -->
    <meta-data android:name="net.hockeyapp.android.appIdentifier"
        android:value="${HOCKEYAPP_APP_ID}" />
```
```groovy
    # build.gradle
    compile 'net.hockeyapp.android:HockeySDK:3.7.0-beta.2'
    manifestPlaceholders = [HOCKEYAPP_APP_ID: "$alpha_hockey_app_id"]
```
```groovy
    # gradle.properties
    alpha_hockey_app_id = 123456789012345678901234567890
```

**Comment by ranterle** [comment]
What is the version code of the app you're looking at and what is the version code of the latest version available on HockeyApp?

**Comment by mesutbeyaztas** [comment]
My app's current version is 10000100 and latest hockey app version 10000200

**Comment by tkirshboim** [comment]
I have the same issue with the 'beta.2' version. With 'beta.1' it works fine. I debugged this a bit this seems to be already fixed here https://github.com/bitstadium/HockeySDK-Android/commit/2dc918f64182616f9a779536765f9046aea45144 but not yet release. Could you please release a new beta so I could see if it works? Thanks!

**Comment by ranterle** [comment]
Thanks for the heads up @tkirshboim - yes this will be fixed in the next beta/release.

**Comment by mesutbeyaztas** [comment]
For now i decide to use beta.1. Thanks for quick and detailed answer @tkirshboim and @ranterle.

**Comment by tkirshboim** [comment]
works for me with the 'rc.1' release.
#113 is a duplicate of this issue
