### ISSUE TITLE
UpdateManager doesn't work on 3.7 beta

### ISSUE THREAD

**Issue by rajuashok** [bitstadium/HockeySDK-Android#113]
I tried using the beta verrsion 3.7.0. The update dialog never shows. I had to revert to 3.6.2.

**Comment by TroubleMakerBen** [comment]
Thanks @rajuashok for raising this. I will look into this.

**Comment by ranterle** [comment]
Looks like this was a bug introduced in Beta 2 - fixed in 2dc918f64182616f9a779536765f9046aea45144

**Comment by ranterle** [comment]
@rajuashok we have just released the first release candidate of 3.7.0: http://hockeyapp.net/blog/2015/12/10/hockeysdk-android-3-7-0-rc-1.html
Can you take a look and see if it works now?

**Comment by tkirshboim** [comment]
I had the same issue - it's fixed in the 'rc.1' release

**Comment by ranterle** [comment]
Thanks for verifying @tkirshboim.
