### ISSUE TITLE
Setting instrumentationKey as third parameter in setup causes IllegalArgumentException when calling UpdateManager.register

### ISSUE THREAD

**Issue by artsterb** [bitstadium/HockeySDK-Android#114]
Looking at Util.getAppIdentifier that is called inside UpdateManager.register, it expects that instrumentation key to be set as meta-data in the manifest.  We should support either a manifest entry for it or setting it as the third parameter on setup.  If both exist, I would say the one sent as a parameter in setup should win.

Repro steps:
1) Call ApplicationInsights.setup(context, application, mCurrentEnvironment.AI_InstrumentationKey);
2) Call UpdateManager.register(this);

If I push a meta-data manifest value for "net.hockeyapp.android.appIdentifier" things work as expected.

**Comment by TroubleMakerBen** [comment]
We have evaluated the issue.
When not using the Android Manifest to store the app identifier, all managers have to be initalised using  register(...)-overloads that include the app identifier.
We should update the readme with this and/or find a more elegant solution than throwing an exception.

**Comment by ranterle** [comment]
I think there is a misunderstanding here: The HockeyApp app identifier has nothing to do with the AI instrumentation key. So registering an instrumentation key with AI will do nothing to the HockeyApp-manager classes.

**Comment by TroubleMakerBen** [comment]
Closing this as it was just a misunderstanding.
