### ISSUE TITLE
FeedbackActivity doesn't show Actionbar

### ISSUE THREAD

**Issue by TroubleMakerBen** [bitstadium/HockeySDK-Android#115]
The Feedback UI doesn't show an action bar.

Confirmed the issue on Nexus 9 running our sample app on Marshmallow.

**Comment by ranterle** [comment]
This is a known issue on all devices with Material design. We are working on a more flexible solution. For the time being, developers will have to present the ActionBar themselves.

**Comment by murki** [comment]
@ranterle could you advise a way to "present the ActionBar themselves" ? I couldn't manage to make it work when using a Theme.AppCompat.Light-derived them (http://android-developers.blogspot.com/2014/10/appcompat-v21-material-design-for-pre.html) and the android.support.v7.widget.Toolbar

**Comment by ranterle** [comment]
@mukri I'm working on something here - unfortunately it's especially tricky supporting appcompat themes and the Toolbar as well.

**Comment by murki** [comment]
@ranterle any chance this will make it into v4.0?

**Comment by ranterle** [comment]
@murki User interface restructuring is still on our backlog - can't promise for 4.0 I'm afraid.

**Comment by ranterle** [comment]
Will be looking into this in the next iteration.

**Comment by jaredsburrows** [comment]
@ranterle This issue has been closed. Was this added in 4.0.2 or are you still working on this?

**Comment by ranterle** [comment]
@jaredsburrows This is on our backlog and will be addressed in a future version, but unfortunately I can't give an ETA or version number for this as of now, sorry.

**Comment by jaredsburrows** [comment]
@ranterle 
Could you make `FeedbackActivity` a `Fragment`? or
Would you allow a PR to add in `AppComp` to extend `FeedbackActivity` with `AppCompatActivity`?
We could possible have both a `FeedbackActivity` and `FeedbackAppCompatActivity`.
