### ISSUE TITLE
FeedbackActivity doesn't support consumer-provided translations

### ISSUE THREAD

**Issue by murki** [bitstadium/HockeySDK-Android#116]
FeedbackActivity / activity_feedback.xml is using the hint values for their EditTexts as well as any other text messages from https://github.com/bitstadium/HockeySDK-Android/blob/develop/hockeysdk/src/main/res/values/strings.xml 

It would be desirable to let the library consumer to provide the strings to be shown on the fields as well as their translations.

**Comment by ranterle** [comment]
Following up on this: It looks like this is fixed already https://github.com/bitstadium/HockeySDK-Android/blob/develop/hockeysdk/src/main/res/layout/activity_feedback.xml#L29
If you don't think of this as fixed, can you explain the situation in a bit more detail?

**Comment by murki** [comment]
Hi @ranterle, our situation is that we localize our app into several more languages that that the ones supported by the HockeyApp out-of-the-box translations. Ideally we could provide the string resource ids for the text used all across HockeyApp (in this example, is the feedback form).
Example jp:
![hockeyapp_jp](https://cloud.githubusercontent.com/assets/216735/12594960/806b4528-c42d-11e5-8dee-a65fee0fa814.png)

**Comment by ranterle** [comment]
As far as I see, all strings in the UI are localizable. You can simply override the [strings](https://github.com/bitstadium/HockeySDK-Android/blob/develop/hockeysdk/src/main/res/values/strings.xml) from our SDK in your app.
All of our strings are localized now, if you find one that is missing, just report it to us or file a PR.

**Comment by murki** [comment]
Oh right, this seemed to have been fixed on v3.7.0 430a8c6, sorry I missed it the first time around. We'll try to upgrade.
