### ISSUE TITLE
NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.trim()' on a null object reference

### ISSUE THREAD

**Issue by the4thfloor** [bitstadium/HockeySDK-Android#118]
In ExceptionHandler#saveException(Throwable exception, Thread thread, CrashManagerListener listener) you can find the following code (lines 133 - 137):

```java
if (listener != null) {
   writeValueToFile(limitedString(listener.getUserID()), filename + ".user");
   writeValueToFile(limitedString(listener.getContact()), filename + ".contact");
   writeValueToFile(listener.getDescription(), filename + ".description");
}
```

The `writeValueToFile` method trims the value, this is okay so far.

But the default value for `listener.getUserID()`, `listener.getContact()` and `listener.getDescription()` are `null`.

You should:

1) check if `value` is `null` or not  *or*
2) make `listener.getUserID()`, `listener.getContact()` and `listener.getDescription()` abstract and @NotNullable

**Comment by ranterle** [comment]
Just to get the right understanding: The issue you're facing is that there's a "null"-String in the values for userID, contact, and description after they're written to the files?

**Comment by the4thfloor** [comment]
Yes, the `CrashManagerListener` returns `null` for this values and if you don't overwrite this methods you get this error.

**Comment by ranterle** [comment]
Ok, I'll be looking into this - thanks.
