### ISSUE TITLE
LoginActivity resource ProGuard warnings in v3.7.0

### ISSUE THREAD

**Issue by niedzielski** [bitstadium/HockeySDK-Android#121]
Upgrading from version v3.6.2 to v3.7.0 has produced two new ProGuard warnings:

    Warning: net.hockeyapp.android.LoginActivity: can't find referenced field 'int input_password' in program class net.hockeyapp.android.R$id
    Warning: net.hockeyapp.android.LoginActivity: can't find referenced field 'int button_login' in program class net.hockeyapp.android.R$id

Am I missing a step? I tried to follow the upgrade notes here[0]. Our project is fully open source and the upgrade diff is tiny[1].

[0] https://github.com/bitstadium/HockeySDK-Android/releases/tag/3.7.0
[1] https://gerrit.wikimedia.org/r/#/c/264255/

**Comment by ranterle** [comment]
Thanks for mentioning. I'll be looking into this.

**Comment by ranterle** [comment]
Using our [Demo project](https://github.com/bitstadium/HockeySDK-AndroidDemo) I can't reproduce the reported issue - it's working fine.
Your project does not seem to use the HockeyApp `LoginActivity` class at all so I wonder why it wouldn't just strip the information.
I noticed your commit in Gerrit dropped all [HockeyApp-related](https://gerrit.wikimedia.org/r/#/c/264255/2/app/proguard-rules.pro) ProGuard config - was this intentional?

**Comment by niedzielski** [comment]
@ranterle, you're right. This is all on our end. We also have a layout file named activity_login.xml which caused the symbols to be dropped. Thanks for checking and the pointer to the demo project, that was helpful.

It was intentional to drop the HA ProGuard configuration since you now distribute an Android archive instead of a jar.

**Comment by joaocsousa** [comment]
@niedzielski I'm having the same issue and I'm having trouble fixing it. Can you explain briefly what the problem was in your case and how you solved it? Do you still need those hockey app specific proguard rules?

**Comment by ranterle** [comment]
Just a quick heads up on this: We are currently not shipping any specific ProGuard configuration with our Android archive. We're working on getting this fixed.

**Comment by niedzielski** [comment]
@joaocsousa, we had an Activity layout resource file named activity_login.xml that conflicted with an identically named filed in the new HockeyApp library. We renamed our copy to activity_foo_login.xml and updated our call [Activity.setContentView()](https://github.com/wikimedia/apps-android-wikipedia/commit/ffc31de0a54447d1562400865e3cfa32c5b01314#diff-7998521a60cfc1cafeb3ae0c7199bb61L66).

@ranterle, oh nuts. We must have lucked out. Thanks for the heads up!

**Comment by ehlkej** [comment]
@ranterle it would be great if you could name your library resources with some sort of qualifier to avoid conflicting with IDs that your host app might use. Apps shouldn't really have to worry about naming conflicts with their third party libraries.

**Comment by ranterle** [comment]
@ehlkej resource IDs from our SDK should be in a different namespace than those from apps. Can you post the details and some sample code of the problem here or [create a support request](http://support.hockeyapp.net) and I'll look into them?

**Comment by ranterle** [comment]
@ehlkej @niedzielski @joaocsousa  Looking into that, we will soon have a PR and 3.7.1 release which fixes our ProGuard shortcomings. Sorry for the trouble. Our testing didn't reveal any problems before, we will extend our review process to make sure it doesn't happen again.

**Comment by duckinferno** [comment]
Thank you @ranterle - top notch responding :)
I can confirm that renaming our activity_login.xml fixes this issue.

**Comment by ranterle** [comment]
Please have a look at #132 which addresses this issue.
