### ISSUE TITLE
Add overload that takes CrashManagerListener to CrashManager.register()

### ISSUE THREAD

**Issue by murki** [bitstadium/HockeySDK-Android#123]
With the [3.7.0 release](https://github.com/bitstadium/HockeySDK-Android/releases/tag/3.7.0), new `register()` overloads were added to `CrashManager`, `UpdateManager`, `FeedbackManager`, and `LoginManager`. 

For `CrashManager` though there is no way to use the new gradle manifestPlaceholders capabilities if a CrashManagerListener is also needed when registering.

**Comment by ranterle** [comment]
We only added the most commonly used `register()` calls with the simplified parameter list. We might include the call with a `CrashManagerListener` in the future.

Until then, you can always use [`Util.getAppIdentifier()`](https://github.com/bitstadium/HockeySDK-Android/blob/develop/hockeysdk/src/main/java/net/hockeyapp/android/utils/Util.java#L250) to retrieve the app identifier string injected through the manifestPlaceholders from the build.gradle file.

**Comment by murki** [comment]
Thanks, @ranterle that works for now. Hopefully this will be added in the future though.
