### ISSUE TITLE
Misleading message: Couldn't create HockeyApp Storage dir

### ISSUE THREAD

**Issue by stari4ek** [bitstadium/HockeySDK-Android#128]
I'm getting multiple messages, which looks like a problem but it's not

> 02-10 22:27:02.433 13626-13626/by.stari4ek.tvirl.debug D/HockeyApp: Couldn't create HockeyApp Storage dir
> 02-10 22:27:02.434 13626-13626/by.stari4ek.tvirl.debug D/HockeyApp: Couldn't create HockeyApp Storage dir
> 02-10 22:27:02.439 13626-13669/by.stari4ek.tvirl.debug D/HockeyApp: Couldn't create HockeyApp Storage dir

Since `File.mkdirs()` returns False if directory exists already we will get bunch of messages each time `getHockeyAppStorageDir()` is called

```    
public static File getHockeyAppStorageDir() {
        File externalStorage = Environment.getExternalStorageDirectory();

        File dir = new File(externalStorage.getAbsolutePath() + "/" + Constants.TAG);
        Boolean success = dir.mkdirs();
        if (!success) {
            Log.d(TAG, "Couldn't create HockeyApp Storage dir");
        }
```

It's better to check if it exists already

**Comment by ranterle** [comment]
@stari4ek thanks for reporting this, I'll be looking into a fix for this soon.
