### ISSUE TITLE
Default Feedback notification isn't visible on Android TV

### ISSUE THREAD

**Issue by stari4ek** [bitstadium/HockeySDK-Android#129]
Android TV doesn't support notifications in the status bar.
Currently HockeyApp use `buildNotificationPreHoneycomb` to build it.
Of course it's possible to provide listener and do own processing, but it would be nice to have default one (toast?)

* android TV emulator, API 21

**Comment by ranterle** [comment]
Hi @stari4ek - we don't officially support Android TV with our SDK as of yet - we are working on this.
On that note, can you tell us a bit more on where and how you are using HockeyApp on Android TV? Feel free to create a support ticket at http://support.hockeyapp.net if you want to share private information.

**Comment by stari4ek** [comment]
I use it for crash reporting. Right now I'm working on "report a problem" using feedback feature.
It's "TV input" app with 2 configuration-like activity and service for playback.

**Comment by ranterle** [comment]
Closing this as TV support is not official for us right now. Feel free to file a PR with changes.
