### ISSUE TITLE
CrashManager uses wrong text resource for positive dialog button

### ISSUE THREAD

**Issue by tkorri** [bitstadium/HockeySDK-Android#139]
CrashManager.showDialog sets R.string.hockeyapp_dialog_positive_button, instead
of R.string.hockeyapp_crash_dialog_positive_button, as the positive dialog button text resource.

This makes the crash dialog show OK for the positive button instead of Send.

**Comment by ranterle** [comment]
Hey, nice catch - thanks for notifying us.
