### ISSUE TITLE
Remove tools:ignore="allowBackup" from AndroidManifest

### ISSUE THREAD

**Issue by degill** [bitstadium/HockeySDK-Android#141]
First of all, applications should handle allowBackup and other attributes within the `<application>` tag in the AndroidManifest on their own IMHO. 

Additionally, I think the `tools:ignore` directive is misplaced here because it is for XML other than the AndroidManifest as it is nowhere stated in the ManifestMerger documentation (https://sites.google.com/a/android.com/tools/tech-docs/new-build-system/user-guide/manifest-merger) but rather in the tools attributes doc (https://sites.google.com/a/android.com/tools/tech-docs/tools-attributes). As stated there it is only used by lint and not by the ManifestMerger.

Other libraries (popular ones like those from square: https://github.com/square) also usually do have an empty `<application>` tag thus moving the need for any customisation to the application and away from the library.

I am stating this because I have an unexpected problem: 
I have a dependency (call it 'ALibrary') declared in my build.gradle which does have 
```
android:allowBackup="true" android:label="@string/app_name"
```
in its AndroidManifest (which is a mistake IMO). 

I do have `tools:replace="allowBackup, label"` in my AndroidManifests `<application>` and that works *only* if the dependency on hockeyApp (`compile '...'`) is *below* the mentioned ALibrary within the build.gradle. If it is *above* it, the manifest merger claims that there are errors, because two AndroidManifests declare allowBackup/label even though I already have `tools:replace="allowBackup, label"` attribute included. 

I can only conclude that this is coming from the `"tools:ignore"` attribute declared in the AndroidManifest in the HockeySdk which disturbs the ManifestMerger.

Please correct me if Im wrong.

**Comment by ranterle** [comment]
Hi @degill, I remember at one point not specifying this caused a lint error, so we introduced the tools:ignore flag. For some reason, if I remove it now altogether – as proposed by you – it doesn't even generate a warning anymore – even though my local `lint --show` lists it as a warning:

```
AllowBackup
-----------
Summary: Missing allowBackup attribute

Priority: 3 / 10
Severity: Warning
Category: Security
```

Running it through a different build tools version on Travis didn't yield any more problems so I will happily remove the tools-instruction, pending final checks. Should be in our next bugfix release, which is due soon.
