### ISSUE TITLE
Fail to build hockeyapp with Proguard

### ISSUE THREAD

**Issue by jeffrey-garcia** [bitstadium/HockeySDK-Android#145]
Build fails........

Warning: net.hockeyapp.android.Constants: can't find referenced field 'java.lang.String[] SUPPORTED_ABIS' in library class android.os.Build
Warning: net.hockeyapp.android.UpdateActivity: can't find referenced method 'void requestPermissions(java.lang.String[],int)' in program class net.hockeyapp.android.UpdateActivity
Warning: net.hockeyapp.android.UpdateFragment: can't find referenced method 'int checkSelfPermission(java.lang.String)' in library class android.app.Activity
Warning: net.hockeyapp.android.UpdateFragment: can't find referenced method 'void requestPermissions(java.lang.String[],int)' in program class net.hockeyapp.android.UpdateFragment
Warning: net.hockeyapp.android.views.AttachmentView: can't find referenced method 'android.graphics.drawable.Drawable getDrawable(int,android.content.res.Resources$Theme)' in library class android.content.res.Resources
Warning: there were 2 unresolved references to program class members.
         Your input classes appear to be inconsistent.
         You may need to recompile the code.
         (http://proguard.sourceforge.net/manual/troubleshooting.html#unresolvedprogramclassmember)
Warning: there were 3 unresolved references to library class members.
         You probably need to update the library versions.
         (http://proguard.sourceforge.net/manual/troubleshooting.html#unresolvedlibraryclassmember)
Exception while processing task 
java.io.IOException: Please correct the above warnings first.
	at proguard.Initializer.execute(Initializer.java:473)
	at proguard.ProGuard.initialize(ProGuard.java:233)
	at proguard.ProGuard.execute(ProGuard.java:98)
	at proguard.gradle.ProGuardTask.proguard(ProGuardTask.java:1074)
	at com.android.build.gradle.tasks.AndroidProGuardTask.doMinification(AndroidProGuardTask.java:139)
	at com.android.build.gradle.tasks.AndroidProGuardTask$1.run(AndroidProGuardTask.java:115)
	at com.android.builder.tasks.Job.runTask(Job.java:48)
	at com.android.build.gradle.tasks.SimpleWorkQueue$EmptyThreadContext.runTask(SimpleWorkQueue.java:41)
	at com.android.builder.tasks.WorkQueue.run(WorkQueue.java:227)
	at java.lang.Thread.run(Thread.java:745)

FAILURE: Build failed with an exception.

**Comment by ranterle** [comment]
Hi @jeffrey-garcia,
for which version of the Android SDK is this? Can you paste your integration build.gradle file?
If you want to provide sensible information, feel free to open up a [support request](http://support.hockeyapp.net).

Kind regards,
Mat

**Comment by jeffrey-garcia** [comment]
android {
    compileSdkVersion 'Google Inc.:Google APIs:19'
    buildToolsVersion "23.0.0"

    defaultConfig {
	minSdkVersion 14
	targetSdkVersion 14

        // Enabling Multi-Dex support
        multiDexEnabled true
    }
}

**Comment by jeffrey-garcia** [comment]
We workaround this by ignoring the proguard warning on HockeyApp, and also skip the obfuscating of the classes in HockeyApp SDK by the following lines in proguard.cfg:

-dontwarn net.hockeyapp.android.** ; 
-keep public class net.hockeyapp.android.** {
	*;
}

**Comment by ranterle** [comment]
Looking into this we don't see anything why ProGuard should not be working for you. 
Keeping the HockeyApp classes as a workaround should be fine, but I'd still like to be able to reproduce this to really fix the underlying issue.

**Comment by TroubleMakerBen** [comment]
@jeffrey-garcia would it be possible for you to send us a Demo-Project? We would love to reproduce this and find the underlying problem. Having our customers do workarounds is not what we want. ;)
If you have concerns to send us a whole demo-project, please open a support request on our website and send it to us there instead.

Best,
Benjamin

**Comment by sdoward** [comment]
I am experiencing issues with proguard after updating to 3.7.2

> Note: there were 2 references to unknown classes.
      You should check your configuration for typos.
      (http://proguard.sourceforge.net/manual/troubleshooting.html#unknownclass)
Note: there were 3 classes trying to access enclosing classes using reflection.
      You should consider keeping the inner classes attributes
      (using '-keepattributes InnerClasses').
      (http://proguard.sourceforge.net/manual/troubleshooting.html#attributes)
Note: there were 268 unkept descriptor classes in kept class members.
      You should consider explicitly keeping the mentioned classes
      (using '-keep').
      (http://proguard.sourceforge.net/manual/troubleshooting.html#descriptorclass)
Note: there were 14 unresolved dynamic references to classes or interfaces.
      You should check if you need to specify additional program jars.
      (http://proguard.sourceforge.net/manual/troubleshooting.html#dynamicalclass)
Note: there were 6 accesses to class members by means of introspection.
      You should consider explicitly keeping the mentioned class members
      (using '-keep' or '-keepclassmembers').
      (http://proguard.sourceforge.net/manual/troubleshooting.html#dynamicalclassmember)
Warning:there were 2 unresolved references to program class members.
         Your input classes appear to be inconsistent.
         You may need to recompile the code.
         (http://proguard.sourceforge.net/manual/troubleshooting.html#unresolvedprogramclassmember)
Warning:there were 1 unresolved references to library class members.
         You probably need to update the library versions.
         (http://proguard.sourceforge.net/manual/troubleshooting.html#unresolvedlibraryclassmember)
Warning:Exception while processing task java.io.IOException: Please correct the above warnings first.

**Comment by ranterle** [comment]
Hi @sdoward. Unfortunately the error message you pasted does not contain any information on which references are missing and from which module. We can't reproduce this issue at the moment without more information. Can you add information about which modules of the SDK you are using, and attach verbose log output from ProGuard for us to identify the issue?

**Comment by ShreyashPromact** [comment]
I am also getting similar issue. is that any proper solution to that?
