### ISSUE TITLE
Network Connect on Main Thread

### ISSUE THREAD

**Issue by kwikgoal** [bitstadium/HockeySDK-Android#146]
Hockey is throwing an exception when testing in Strict Mode.  Looks as if it is coming from okhttp, and likely requires some change in way Hockey is creating connections via the library.

See https://github.com/square/okhttp/issues/2017 for the description.

Using 3.7.0 of Hockey currently.  Also tried the newest 4.0.0, and still occurs.

04-04 19:38:00.239 7701-7701/com.myapp W/System.err: android.os.NetworkOnMainThreadException
04-04 19:38:00.239 7701-7701/com.myapp W/System.err:     at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1273)
04-04 19:38:00.239 7701-7701/com.myapp W/System.err:     at java.net.InetAddress.lookupHostByName(InetAddress.java:431)
04-04 19:38:00.239 7701-7701/com.myapp W/System.err:     at java.net.InetAddress.getAllByNameImpl(InetAddress.java:252)
04-04 19:38:00.239 7701-7701/com.myapp W/System.err:     at java.net.InetAddress.getAllByName(InetAddress.java:215)
04-04 19:38:00.239 7701-7701/com.myapp W/System.err:     at com.android.okhttp.internal.Network$1.resolveInetAddresses(Network.java:29)
04-04 19:38:00.239 7701-7701/com.myapp W/System.err:     at com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:188)
04-04 19:38:00.239 7701-7701/com.myapp W/System.err:     at com.android.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:157)
04-04 19:38:00.239 7701-7701/com.myapp W/System.err:     at com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:100)
04-04 19:38:00.239 7701-7701/com.myapp W/System.err:     at com.android.okhttp.internal.http.HttpEngine.createNextConnection(HttpEngine.java:357)
04-04 19:38:00.239 7701-7701/com.myapp W/System.err:     at com.android.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:340)
04-04 19:38:00.239 7701-7701/com.myapp W/System.err:     at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:330)
04-04 19:38:00.240 7701-7701/com.myapp W/System.err:     at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:248)
04-04 19:38:00.240 7701-7701/com.myapp W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:433)
04-04 19:38:00.240 7701-7701/com.myapp W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:114)
04-04 19:38:00.240 7701-7701/com.myapp W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:245)
04-04 19:38:00.240 7701-7701/com.myapp W/System.err:     at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:218)
04-04 19:38:00.240 7701-7701/com.myapp W/System.err:     at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java)
04-04 19:38:00.240 7701-7701/com.myapp W/System.err:     at net.hockeyapp.android.utils.HttpURLConnectionBuilder.build(HttpURLConnectionBuilder.java:171)
04-04 19:38:00.240 7701-7701/com.myapp W/System.err:     at net.hockeyapp.android.CrashManager.submitStackTraces(CrashManager.java:334)
04-04 19:38:00.240 7701-7701/com.myapp W/System.err:     at net.hockeyapp.android.CrashManager.submitStackTraces(CrashManager.java:268)

**Comment by ranterle** [comment]
Hi @kwikgoal, thanks for reporting this. For legacy reasons we are submitting our crashes in the simplest way possible. We are working on a new sender architecture already which will also move all network traffic (including submitting crash reports) off the main thread. So far we can give no ETA when this will be finished.
