### ISSUE TITLE
values-zn

### ISSUE THREAD

**Issue by tianyong2** [bitstadium/HockeySDK-Android#154]
Can you add a values-zn?

**Comment by anlinde** [comment]
Where do you want to add what kind of values?

**Comment by TroubleMakerBen** [comment]
Hi @tianyong2,
I'm not sure I understand your question correctly, but I think you are asking for a localization in "ZH" for simplified chinese?

We have additional locales on our backlog but to be honest, I can't give you an ETA for this.
We're happy to receive a pull request with some new localizations.

Benjamin

**Comment by ranterle** [comment]
Closing this in favor of #162
