### ISSUE TITLE
Expose method to explicitly trigger update check

### ISSUE THREAD

**Issue by chrwend** [bitstadium/HockeySDK-Android#155]
Hi guys,

I was wondering if you guys could expose a way to trigger an update check. It seems like the HockeySDK for iOS already supports that (`checkForUpdate()`). 

Cheers

**Comment by TroubleMakerBen** [comment]
Each UpdateManager.register()-call checks for updates, totally possible to call it multiple times.

It'd be neat to have that as an explicit API, though.

**Comment by ranterle** [comment]
Will have a look into this.

**Comment by ranterle** [comment]
Put this on our internal backlog. Closing here for now.
