### ISSUE TITLE
Can't get user email from LoginManager

### ISSUE THREAD

**Issue by keithburgoyne** [bitstadium/HockeySDK-Android#157]
Submitting crash reports via Android requires we set the user's email information in a CrashMetaData instance in order to have the Contact column filled in on the Crashes section of the website.

iOS seems to do this automatically, but Android does not. To help work around this, it would be fantastic if the `LoginManager` class could provide a means of retrieving the HockeyApp email address the user used to authenticate. That way we could execute something like:

```
final CrashMetaData metaData = new CrashMetaData();
metaData.setUserEmail(LoginManager.getUserEmail());
metaData.setUserDescription("Something happened.");
...
CrashManager.handleUserInput(
				CrashManagerUserInput.CrashManagerUserInputSend,
					metaData,
					null,
					new WeakReference<Context>(activity),
					false
);
```

... and the crash reports will appear with the correct contact information for authenticated users.

**Comment by ranterle** [comment]
Hi @keithburgoyne I can see your point – as of now are modules are very independent of each other. You are very welcome to file a PR if you have something ready – otherwise we will put it on our backlog.

**Comment by ranterle** [comment]
Put on our internal backlog. Closing this for now.

**Comment by laalto** [comment]
For what it's worth, I was looking for something similar and ended up creating a PR to create such a method in `LoginManager`. https://github.com/bitstadium/HockeySDK-Android/pull/188
