### ISSUE TITLE
Hockey Updates are very slow

### ISSUE THREAD

**Issue by pietrini** [bitstadium/HockeySDK-Android#160]
Since the 4.0.x releases, the time before the update dialog prompt on android is just crazy.

06-13 17:05:01.542 D/Main: HockeyApp
06-13 17:05:01.555 D/HockeyApp: Looking for exceptions in: /data/user/0/ch.rts.player.beta/files
06-13 17:05:01.556 D/HockeyApp: Current handler class = com.android.internal.os.RuntimeInit$UncaughtHandler
06-13 17:05:01.665 D/HockeyApp: Looking for exceptions in: /data/user/0/ch.rts.player.beta/files
06-13 17:05:01.666 D/HockeyApp: Current handler class = net.hockeyapp.android.ExceptionHandler
06-13 17:13:32.295 V/HockeyUpdate: Received Update Info
06-13 17:13:32.296 V/HockeyUpdate: Caching is enabled. Setting version to cached one.

I unfortunately can't show you more logs because the SDK didn't send more messages.

It takes more than 8 minutes for the SDK to check if a new update is available. I've test it with the 4.0.0 and 4.0.1 version and even with the last 4.1.0-beta.2 we have the same problem, on a nexus 6P, 5X, 5.

**Comment by ranterle** [comment]
Hi @pietrini can you verify this issue is not also affecting the previous releases? We haven't seen any such issues, so I have to assume some kind of other issue. Is your network fine?

**Comment by pietrini** [comment]
Hi, yes the network is fine and we test it on wifi and cellular data. I wouldn't have create a ticket otherwise. We used the build 3.6.2 before and it works fine.

**Comment by ranterle** [comment]
Thanks for providing the details about your connection and the earlier working versions. This looks very odd to me. Can provide the integration code you are using for HockeySDK, such as where and how you set up the UpdateManager? If this contains confidential code, feel free to open up a support ticket at https://support.hockeyapp.net

**Comment by pietrini** [comment]
done : https://support.hockeyapp.net/discussions/problems/58335-hockey-updates-are-very-slow

**Comment by ranterle** [comment]
Thanks, I'll close this here and will come back to you in support.
