### ISSUE TITLE
UpdateManager does not show dialogs in Android N

### ISSUE THREAD

**Issue by boguscoder** [bitstadium/HockeySDK-Android#161]
Even if update is available and isDialogRequired is set to true there is no update prompt on Android N (preview 1,2,3). Same app, same code on lower Android versions works as expected

**Comment by ranterle** [comment]
Thanks @boguscoder for notifying us. In our testing of all developer previews of Android N so far everything worked fine. Can you please share information like device model and your app integration code with us, so we can isolate the issue? If you need to share non-public information, you can also open up a support request at https://support.hockeyapp.net

Thanks,
Mat

**Comment by boguscoder** [comment]
I have to apologize, there must have been a downtime or deployment issue on our side at the time of testing. I've tested again few devices and all works as expected

**Comment by boguscoder** [comment]
Sorry for poking into bug's corpse, but I just hit this again and debugged to nail the root cause. So the issue only repros when I install app from HockeyApp app because installedFromMarket call would  return true in this case, at least on my device. When installed from adb all subsequent update prompts are working as expected

**Comment by ranterle** [comment]
@boguscoder What kind of device do you have? What does `context.getPackageManager().getInstallerPackageName(context.getPackageName())` return on your device, when you install an app via the HockeyApp app?

**Comment by boguscoder** [comment]
Im using Nexus 6p on final Android N.
It returns smth like com.google.android.packageinsataller

**Comment by boguscoder** [comment]
The workaround I have used so far was to let HockeyApp app download every app I need but cancell installation and manually install with adb from Downloads

**Comment by ranterle** [comment]
@boguscoder I'm able to reproduce the issue, in the sense that:
In my testing on Android N, our mechanism to determine the installer package name before Android N returned `null`, whereas in Android N it returns `com.google.android.packageinstaller` on my Nexus 5X.
Looking to implement a fix for this.

**Comment by Brian-Kaplan** [comment]
@ranterle Having the same issue here as well. Any idea on when you will have a fix for it?

**Comment by ranterle** [comment]
@Brian-Kaplan I'm working on that, unfortunately no ETA possible, but real close.

**Comment by Brian-Kaplan** [comment]
@ranterle Awesome, thanks for looking into a fix for us!
