### ISSUE TITLE
UpdateManager does not remove downloaded APKs

### ISSUE THREAD

**Issue by Shyish** [bitstadium/HockeySDK-Android#164]
When using the UpdateManager for your app after several updates the devices start to get full because of the old leftover apks downloaded and not cleaned.

Please consider using proper naming (some code + date) so the old apks can be removed after successfully downloaded a new one.

I could try to create a pull request to DownloadFileTask if needed.
Cheers.

**Comment by ranterle** [comment]
Thanks @Shyish for the comment. As you point out it is hard to find out which APKs can be purged from within the SDK. Our users use a lot of different versionName & versionCode scheme combinations, so in the past UUIDs were the thing that caused the least trouble. We'll be looking into this.

**Comment by ranterle** [comment]
I've added this to our internal backlog. Since there's no easy fix we can't promise an ETA.
