### ISSUE TITLE
Memory leak in MetricsManager when initialized with Activity context

### ISSUE THREAD

**Issue by anthonycr** [bitstadium/HockeySDK-Android#166]
The new API for the `MetricsManager` suggests that you initialize it with an Activity context (`MetricsManager.register(Context, Application)`). Documentation does not specify that an Activity context is required, but the language of the docs [found here](https://www.hockeyapp.net/help/sdk/android/4.1.0-beta.2/net/hockeyapp/android/metrics/MetricsManager.html#register-android.content.Context-android.app.Application-),  indicate that it is suggested:
```java
context - The context to use. Usually your activity.
```

However, if initialized with an Activity, a memory leak will occur (see the screenshot of the leak in LeakCanary below):
![hockey_app_memory_leak](https://cloud.githubusercontent.com/assets/1966779/16658133/2bbdb37c-4433-11e6-848e-b06c184036a0.png)

Digging around in the code, it is clear that `WeakReference` is used in several places to prevent the `Context` parameter from leaking, as well as the `Application` object (although technically not necessary for the Application object). However, there is one case that was missed, as shown in the leak screenshot. 

In the register method, `MetricsManager`[ creates a new `TelemetryContext`](https://github.com/bitstadium/HockeySDK-Android/blob/develop/hockeysdk/src/main/java/net/hockeyapp/android/metrics/MetricsManager.java#L194), which is then [stored in a static field](https://github.com/bitstadium/HockeySDK-Android/blob/develop/hockeysdk/src/main/java/net/hockeyapp/android/metrics/MetricsManager.java#L93). `TelemetryContext` takes a `Context` as a parameter in its constructor and [stores that in a member variable](https://github.com/bitstadium/HockeySDK-Android/blob/develop/hockeysdk/src/main/java/net/hockeyapp/android/metrics/TelemetryContext.java#L113). Because of this, the static `TelemetryContext` outlives the Activity and leaks it. Additionally, because the `MetricsManager.register()` method only initializes its instance once, this leaked Activity will survive until the application is removed from memory.

Thankfully, it appears that simply registering the MetricsManager using Application context rather than Activity context seems to have no negative repercussions, which is what we are currently using instead of the Activity. However, the fact that the register method takes both a `Context` and an `Application` (when the Application object already contains a valid context) makes it seem like there might be something we missed and that an Activity context might actually be necessary.

If an Activity context is not necessary, it would potentially be better if the register method just took in the `Application` object and used that as the context needed in the metrics code: `MetricsManager.register(Application)`

If an Activity is truly necessary, then it might be better to change the parameter from `Context` to `Activity` to enforce this, as well as add some more documentation (`MetricsManager.register(Activity, Application)`). Additionally, with the use of weak references, this Activity object would go away as soon as an activity gets destroyed, rendering it useless for the metrics manager. In this case, it would make sense to be able to re-initialize the `MetricsManager` with the current `Activity` in some lifecycle event like `onResume` so that the foreground activity is always available.

**Comment by ranterle** [comment]
Hi @anthonycr thanks for reporting this and your thorough investigation so far - I will look into this.
First things first: Using the `application` instance should be fine, if you encounter any problems, please do let me know.

I will make sure our documentation reflects this, and will look into fixing the leak. Like you said, this will probably involve deprecating the old API (I remember some legacy decisions why this still is in place) and changing `MetricsManager.register()` to only take application instance.

**Comment by anthonycr** [comment]
Great! Thanks for following up so quickly, we'll continue to use the application context then

**Comment by ranterle** [comment]
Fixed in 4.0.2
