### ISSUE TITLE
Optional upgrade dialog can be closed without triggering an onCancel in the UpdateManagerListener

### ISSUE THREAD

**Issue by nbonavia** [bitstadium/HockeySDK-Android#168]
I am using hockeyapp sdk together with the UpdateManagerListener so that I'll be notified whenever a user interacts with the process. Whenever the user is prompted to optionally upgrade the app, the user can cancel the dialog in 2 ways, which are: -
- Pressing the back button
- Clicking anywhere outside the dialog button.

May I suggest 2 options:
1. (Simpler Option) In the Alert Dialog, set setCanceledOnTouchOutside(false); so that tapping outside the dialog area will not dismiss the dialog. Override the back button and disable the user from closing the dialog when pressing the back key.
2. Tie the dialow behavioiur with the UpdateManagerListener, so that the onCancel method will be invoked when the user cancels the dialog in any of the above ways.

**Comment by nbonavia** [comment]
BTW, I am using Version 4.1.0-beta.2

**Comment by ranterle** [comment]
Thanks for notifying us, I will be looking into this.
