### ISSUE TITLE
The UpdateManagerListener does not get notified if no update check is going to be performed

### ISSUE THREAD

**Issue by nbonavia** [bitstadium/HockeySDK-Android#169]
The update manager does not Always check for updates, however when we attach the UpdateManagerListener, it would be great to have a callback e.g. onUpdateCheckSkipped so that the listener will be informed that update check will not be performed in this round. This allows a smoother behaviour on certain tasks bound with update check decisions.

**Comment by nbonavia** [comment]
BTW, I am using Version 4.1.0-beta.2

**Comment by ranterle** [comment]
We are caching the results for the update manager check - will be looking into the appropriate changes. Feel free to open a PR with the changes if you have them ready.
