### ISSUE TITLE
Upgrading to gradle 2.14 breaks hockey upload

### ISSUE THREAD

**Issue by stephenroberts82** [bitstadium/HockeySDK-Android#175]
When executing

./gradlew uploadDevReleaseToHockeyApp

 I get:

:instaply-android:uploadDevReleaseToHockeyApp FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':instaply-android:uploadDevReleaseToHockeyApp'.
> No service of type ProgressLoggerFactory available in ProjectScopeServices.

It was working fine with 2.10.

**Comment by ranterle** [comment]
Hi @stephenroberts82,
the SDK doesn't offer this task, what plugin do you use that adds this task?

Best,
Mat

**Comment by stephenroberts82** [comment]
Yes, apologies, it comes from another plugin.
