### ISSUE TITLE
WRITE_EXTERNAL_STORAGE permission is not merged properly when using android:maxSdkVersion

### ISSUE THREAD

**Issue by tranb3r** [bitstadium/HockeySDK-Android#176]
My app needs the WRITE_EXTERNAL_STORAGE permission on Android versions <= 18.
So my app manifest contains the following line:
<`uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" android:maxSdkVersion="18" />`

It looks like HockeyApp does not properly merge its own WRITE_EXTERNAL_STORAGE permission in this situation. Indeed the final manifest (after merge) still contains the maxSdkVersion filter from the orginal manifest. As a consequence, the in-app update mechanism does not work (on Android versions > 18).

Could you please take a look ?

By the way, I'm using hockeyapp with Xamarin... I don't know if it makes a difference ?

Thanks

**Comment by ranterle** [comment]
Hi @tranb3r - so the quick solution to me looks like you could just remove the `android:maxSdkVersion` attribute from your permission requirement if you ship the HockeySDK anyway.
I will look into updating our Manifest merging strategy so this gets handled intuitively.

**Comment by ranterle** [comment]
After looking at the [Manifest Merger documentation](https://developer.android.com/studio/build/manifest-merge.html) I don't see how we can support this in the SDK. The SDK being a library will always be considered lowest priority for taking part in the merging process so it can't really dictate any changes.
If your app has this kind of permission requirement you will have to remove the `maxSdkVersion` attribute.
