### ISSUE TITLE
Util.isConnectedToNetwork and ConnectivityManager leak

### ISSUE THREAD

**Issue by Dimezis** [bitstadium/HockeySDK-Android#177]
Hello,

There's a known leak in Android SDK, related to static `Context` reference inside of `ConnectivityManager`.
HockeySDK depends on it while checking `Util.isConnectedToNetwork(Context)` and passing Activity reference as a Context. Although you have the `WeakReference` while accepting the Activity reference, of course you still pass a strong reference to that method, hence there's a leak on HockeyApp registration if we `finish()` the Activity.

Can you please pass `context.getApplicationContext()` to the `ConnectivityManager`? I can make a pull request if needed.

**Comment by partition** [comment]
Upvoted. This is huge.

Any possibility to ship it quickly? It's causing issues for me as well.

**Comment by ranterle** [comment]
Hi @Dimezis, I was not able to reproduce this issue using LeakCanary as to the description you sent. Can you provide a sample where this leak is reproducible?
If you look into the [implementation](https://github.com/bitstadium/HockeySDK-Android/blob/652511d18ae81b37d13540bba176d57c3c1c2da2/hockeysdk/src/main/java/net/hockeyapp/android/utils/Util.java#L266-L273), we don't pass anything to the `ConnectivityManager`. Of course we appreciate a PR, if you can take the time.

Best,
Mat

**Comment by Dimezis** [comment]
Yes, for some reason it is not 100% reproducible, but I can send you an example a bit later.
We also track it with LeakCanary.

By "passing" I mean that you are calling `getSystemService` on Activity context.

Ok then, I'll make a PR and try to provide more reliable steps.

**Comment by ranterle** [comment]
Ok, thanks I was figuring something along the lines. This helped: https://github.com/mapbox/mapbox-gl-native/issues/3525
No need for a PR then, I'll try to include the fix in our next release.
