### ISSUE TITLE
WRITE_EXTERNAL_STORAGE should be optional at most

### ISSUE THREAD

**Issue by pvegh** [bitstadium/HockeySDK-Android#181]
An extra permission in our app which otherwise would not needed.
For what exactly is this used in the SDK? Crashes could be written in the private storage of the app without permission and maybe copied to Documents or Downloads if needed to be shared?

Seems like this this perm came with 4.0.2, it is not needed with 4.0.1.

Our aim is not to have this perm in the app at all.

**Comment by ranterle** [comment]
Hi @pvegh - this permission is required for the update feature. You can use the following instructions if you don't need the feature and don't want to require the permission: https://github.com/bitstadium/HockeySDK-Android#471-removing-external-storage-permission

**Comment by pvegh** [comment]
Alright thanks for the info.
