### ISSUE TITLE
VersionHelper.loadVersions() uses apk VersionCode instead of APP_VERSION

### ISSUE THREAD

**Issue by riguru** [bitstadium/HockeySDK-Android#187]
VersionHelper.loadVersions() uses apk VersionCode instead of APP_VERSION.
though in CheckUpdateTask.doInBackground() uses Constants.APP_VERSION.
Constants.APP_VERSION should be used consistently.

**Comment by ranterle** [comment]
Can you point us to the line of code you think is wrong?
https://github.com/bitstadium/HockeySDK-Android/blob/82b617cf1b2292b4e03a0e24675c4ffa109ea20a/hockeysdk/src/main/java/net/hockeyapp/android/utils/VersionHelper.java#L46-L69
VersionHelper.loadVersions() is not using the version of the app at hand but it's loading and sorting the versions the HockeyApp API lists as available for the app.

**Comment by riguru** [comment]
so updateManager is relying on apk versionCode if BuildNumber is not provided?

**Comment by ranterle** [comment]
I don't quite understand your question - the we don't inspect the APK version code in the SDK at all, as we don't have the APK. What do you mean by the BuildNumber is not provided? Can you please explain your scenario in more detail? Feel free to open a [support request](https://support.hockeyapp.net) if it contains sensible information.
