### ISSUE TITLE
FeedbackActivity limited to responding to previously submitted feedback

### ISSUE THREAD

**Issue by awhlee** [bitstadium/HockeySDK-Android#192]
I'm using the FeedbackActivity via:

FeedbackManager.showFeedbackActivity(context);

and it works fine the first time.  Any subsequent launches of the FeedbackActivity only allows a user to add a response top previously submitted feedback. There is no option to submit new feedback or view a list of previous feedback.  Am I doing something wrong?

**Comment by ranterle** [comment]
Hi @awhlee, this was the intended behavior before.
With version 4.1.2 of the SDK, you can take advantage of the following API `FeedbackManagerListener.shouldCreateNewFeedbackThread()`: https://www.hockeyapp.net/help/sdk/android/4.1.2/net/hockeyapp/android/FeedbackManagerListener.html#shouldCreateNewFeedbackThread--

Introduced by #189

**Comment by awhlee** [comment]
Cool thanks.  I should have caught this. The docs do indicate that the user will be able to see their previously submitted feedback too.  Its unclear how to enable this.  Is there a way?

"When the user taps on the feedback button it will launch the HockeySDK's feedback interface, where the user can create a new feedback discussion, add screenshots or other files for reference, and act on their previous feedback conversations."

**Comment by awhlee** [comment]
Sorry, I wasn't entirely clear.  Once a user submits multiple feedbacks...is there a way to show all of them in a list within FeedbackActivity?

**Comment by ranterle** [comment]
Unfortunately not - currently, the `shouldCreateNewFeedbackThread()` API only supports creating a new feedback thread, we don't keep track of past threads in the SDK, so there's no way of showing the past threads.
