### ISSUE TITLE
HockeyApp is crashing the app

### ISSUE THREAD

**Issue by HEBOS** [bitstadium/HockeySDK-Android#198]
I'm having troubles with current HockeyApp SDK 4.1.0
It was really hard to track down who is responsible for application crash, because application crashed in different parts of the code.
It seams that http client conflicts somewhere with HockeyApp crash manager.
 
My code is:
 
// Get HockeyApp ID
            var hockeyAppId = Resources.GetString(Resource.String.HockeyAppId);
 
            // Register HockeyApp to collect crashes
            //HockeyApp.Android.CrashManager.Register(this, hockeyAppId, new CustomCrashManagerListener());          While line is commented, application works as expected.
 
            // Register HockeyApp to collect metrics
            HockeyApp.Android.Metrics.MetricsManager.Register(this, Application);
 
            // Get time when user started app
            HockeyApp.Android.Tracking.StartUsage(this);
 
I'm using CustomCrashManagerListener since I don't want having Crash Manager popup to be shown at the start of the app, but crash sent to HockeyApp silently.
 
public class CustomCrashManagerListener : HockeyApp.Android.CrashManagerListener
    {
        public override bool ShouldAutoUploadCrashes()
        {
            return true;
        }
    }
 
 
Here is exceprt from LogCat:
 
08-25 14:33:36.999 E/StrictMode(17335): A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
08-25 14:33:36.999 E/StrictMode(17335): java.lang.Throwable: Explicit termination method 'close' not called
08-25 14:33:36.999 E/StrictMode(17335):           at dalvik.system.CloseGuard.open(CloseGuard.java:184)
08-25 14:33:36.999 E/StrictMode(17335):           at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:278)
08-25 14:33:36.999 E/StrictMode(17335):           at com.android.okhttp.Connection.upgradeToTls(Connection.java:146)
08-25 14:33:36.999 E/StrictMode(17335):           at com.android.okhttp.Connection.connect(Connection.java:107)
08-25 14:33:36.999 E/StrictMode(17335):           at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:294)
08-25 14:33:36.999 E/StrictMode(17335):           at com.android.okhttp.internal.http.HttpEngine.sendSocketRequest(HttpEngine.java:255)
08-25 14:33:36.999 E/StrictMode(17335):           at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:206)
08-25 14:33:36.999 E/StrictMode(17335):           at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:345)
08-25 14:33:36.999 E/StrictMode(17335):           at com.android.okhttp.internal.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:89)
08-25 14:33:36.999 E/StrictMode(17335):           at com.android.okhttp.internal.http.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:197)
08-25 14:33:36.999 E/StrictMode(17335):           at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:254)
08-25 14:33:36.999 E/StrictMode(17335):           at net.hockeyapp.android.metrics.Sender.getWriter(Sender.java:397)
08-25 14:33:36.999 E/StrictMode(17335):           at net.hockeyapp.android.metrics.Sender.logRequest(Sender.java:319)
08-25 14:33:36.999 E/StrictMode(17335):           at net.hockeyapp.android.metrics.Sender.send(Sender.java:141)
08-25 14:33:36.999 E/StrictMode(17335):           at net.hockeyapp.android.metrics.Sender.sendAvailableFiles(Sender.java:126)
08-25 14:33:36.999 E/StrictMode(17335):           at net.hockeyapp.android.metrics.Sender$1.doInBackground(Sender.java:86)
08-25 14:33:36.999 E/StrictMode(17335):           at net.hockeyapp.android.metrics.Sender$1.doInBackground(Sender.java:82)
08-25 14:33:36.999 E/StrictMode(17335):           at android.os.AsyncTask$2.call(AsyncTask.java:288)
08-25 14:33:36.999 E/StrictMode(17335):           at java.util.concurrent.FutureTask.run(FutureTask.java:237)
08-25 14:33:36.999 E/StrictMode(17335):           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
08-25 14:33:36.999 E/StrictMode(17335):           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
08-25 14:33:36.999 E/StrictMode(17335):           at java.lang.Thread.run(Thread.java:841)
08-25 14:33:37.004 D/Mono    (17335): Assembly Ref addref HockeySDK.AndroidBindings[0x5e7eb310] -> System[0x68321488]: 20

**Comment by ranterle** [comment]
Hi @HEBOS, is the crash because of StrictMode (which shouldn't be run in production mode, or at least not configured to kill the application then) or did you only find it through StrictMode?

**Comment by TroubleMakerBen** [comment]
Hi @HEBOS,

any news on this. If we don't hear back, I will close this issue.

Best,
Benjamin

**Comment by HEBOS** [comment]
I almost abandoned HockeyApp and moved to Firebase, but because of your comment, I gave one more try and voila, it is working now.
I don't know what you guys have done, but it is working.

**Comment by TroubleMakerBen** [comment]
Hey @HEBOS ,

Thank you for giving HockeyApp a chance =)
Apologies for the initial delay on our response, we usually respond within 24hrs.

Best,
Benjamin
