### ISSUE TITLE
Authentication can be bypassed by putting the app in the background

### ISSUE THREAD

**Issue by martinbonnin** [bitstadium/HockeySDK-Android#204]
Is it just me or is it possible to just put the app in the background to make the login dialog disappear ??

**Comment by martinbonnin** [comment]
This is due to the FLAG_ACTIVITY_NO_HISTORY flag on the LoginActivity. Any idea the rationale behind that ?

**Comment by ranterle** [comment]
@martinbonnin Looking for the rationale behind the `FLAG_ACTIVITY_NO_HISTORY` argument - however, I can not reproduce the issue you are facing. The login activity disappears on reactivation, however, I don't get directed to the protected activity but stay at the root.
Can you share more details like OS version, device type, screenshots, integration code, or ideally, a whole sample project?
If you need to share confidential information, feel free to create a support request at https://support.hockeyapp.net

**Comment by martinbonnin** [comment]
> I don't get directed to the protected activity but stay at the root.

What do you mean by root ? My app has only one single-top activity so when the login activity disappears, it becomes visible. Would the root be my main activity in that case ? I'm using a Pixel phone with Nougat. Right now, I'm using a workaround by listening to the [ActivityLifecycleCallbacks](https://developer.android.com/reference/android/app/Application.html#registerActivityLifecycleCallbacks%28android.app.Application.ActivityLifecycleCallbacks%29) and destroying the app if user is not logged in. It's not nice but it works.

**Comment by erychagov** [comment]
Hi, @martinbonnin 

Could you provide your case for us?
Do you want to protect your application using sdk login page?

Hi, @ranterle

I think that flag FLAG_ACTIVITY_NO_HISTORY has been added so sdk not break usual application navigation stack. Am I right?

**Comment by martinbonnin** [comment]
@erychagov Yes, I'm trying to protect my app with the login page. My app is single-activity. When put in the background from the login page, the login activity is destroyed and the app becomes accessible.

**Comment by TroubleMakerBen** [comment]
This was fixed in 4.1.3 that we released just now. Thx guys!
