### ISSUE TITLE
Crash when using in-app auto-update

### ISSUE THREAD

**Issue by martinbonnin** [bitstadium/HockeySDK-Android#206]
I get the exception below when using the "auto-update" feature :-(. I can go to the download page, download the apk but it crashes just after that.

    android.os.FileUriExposedException: file:///storage/emulated/0/Download/5380e383-5e71-4215-aa37-7f749bbfb965.apk exposed beyond app through Intent.getData()

**Comment by ranterle** [comment]
Hi @martinbonnin this issue was introduced in Android 7.0 - it should be fixed in the latest version of HockeySDK: 4.1.2 - are you running this?

**Comment by martinbonnin** [comment]
@ranterle works fine, thanks, closing this issue
