### ISSUE TITLE
MetricsManager not present in code

### ISSUE THREAD

**Issue by pablichjenkov** [bitstadium/HockeySDK-Android#216]
Hi guys documentation establishes that this class MetricsManager would take care of doing user metrics. However, I don't see it anywhere in code on develop branch. is it in a different branch?

**Comment by ranterle** [comment]
Hi @pablichjenkov you can find the MetricsManager class in its own package `metrics`, see here: https://github.com/bitstadium/HockeySDK-Android/blob/develop/hockeysdk/src/main/java/net/hockeyapp/android/metrics/MetricsManager.java
