### ISSUE TITLE
Session tracking always uses version code

### ISSUE THREAD

**Issue by Luomu** [bitstadium/HockeySDK-Android#219]
It seems the session tracking in user metrics always collects the sessions based on version code.

Normally we can define buildNumber in AndroidManifest (in our case, svn revision) which is used to group crash reports. If no buildNumber is available, versionCode is used. This value is saved in Constants.APP_VERSION (In Constants.java, loadPackageData).

We noticed that our session data never goes to the same place as our crash reports, hockeyapp seems to create a new version based on the app version code if one does not exist. I suspect the cause is
https://github.com/bitstadium/HockeySDK-Android/blob/cd5b3e9af812fba78f075de2453dd371f4a01b81/hockeysdk/src/main/java/net/hockeyapp/android/metrics/TelemetryContext.java#L174
because it only reads versionCode and not APP_VERSION.

**Comment by TroubleMakerBen** [comment]
Hey @Luomu,

thanks for getting in touch.
While you are right about the code sample above, if you set the loglevel to `Lob.Verbose`, you will see that we're actually sending session info with `"ai.application.ver":"1.0.0 (1)"` so we are sending both infos.
That said, we're investigating the issue.
I'll let you know as soon as we found out something.

**Comment by TroubleMakerBen** [comment]
4.1.4 was just released and fixes the issue. =)
