### ISSUE TITLE
Allow Register in Crash/UpdateManager with Listener, without AppId

### ISSUE THREAD

**Issue by shortstuffsushi** [bitstadium/HockeySDK-Android#226]
Currently both `CrashManager` and `UpdateManager` have multiple `register` methods, both of which have a three parameters option allowing me to provide a "listener" type class. However, in order to use that, I have to provide my App_Id, unlike the default `context` method which pulls it from the manifest. In the case that I want to use a listener, I would prefer to not have to have to provide the app identifier. Could you make a separate overload for that case?

**Comment by ranterle** [comment]
It is possible - we have not heard high demand for it. If you want, you can file a PR for it - or I can do it later.
In the meantime, and until we ship a new release, you can use the `Util.getAppIdentifier(Context)` method to get the app identifier the same way the SDK does, e.g.:

```
CrashManager.register(context, Util.getAppIdentifier(context), listener);
```

**Comment by shortstuffsushi** [comment]
Thanks for the quick turnaround on that. I did end up using the Util method suggested, so I'm good for now. Looking forward to not using your internals though ;)
