### ISSUE TITLE
Progress bar is not closed after restoring app

### ISSUE THREAD

**Issue by sirekanyan** [bitstadium/HockeySDK-Android#232]
1. Open FeedbackActivity
2. Fill all required fields and add an attachment
3. Click "send feedback" button
4. Hide application when progress bar appeared
5. Restore application
6. Progress bar is staying visible forever (actually feedback was successfully sent to HockeyApp)

Using net.hockeyapp.android:HockeySDK:4.1.3

![photo_2017-04-27_15-01-45](https://cloud.githubusercontent.com/assets/2663397/25482474/b1f599be-2b5a-11e7-850b-65abffd3bf36.jpg)

**Comment by TroubleMakerBen** [comment]
Hey Vadik, 
thanks for getting in touch and providing the steps to repro the issue.
Apologies for issues this causes you.
We are looking into this and I'll let you know.

Best,
Benny

**Comment by TroubleMakerBen** [comment]
Version 4.1.6 is out and fixes this! 🎉
