### ISSUE TITLE
Feedback activity doesn't use current time zone

### ISSUE THREAD

**Issue by sirekanyan** [bitstadium/HockeySDK-Android#234]
Please, see screenshot:
![screenshot](https://cloud.githubusercontent.com/assets/2663397/25594449/4b52f0e0-2ec9-11e7-8679-f38cd83a3fb3.png)

**Comment by TroubleMakerBen** [comment]
Hey @sirekanyan,

thx for this. We're working on a fix that works across all API levels.
Thanks for the initial PR and for the suggestion about how to fix this.
We appreciate your support!

Benny

**Comment by TroubleMakerBen** [comment]
Version 4.1.6 is out and fixes this! 🎉

**Comment by sirekanyan** [comment]
@TroubleMakerBen, I think you mean version 4.1.5?

**Comment by TroubleMakerBen** [comment]
Dang, exactly! It's 4.1.5!
(4.1.6 is the iOS SDK release...oh all the releases! ;))
