### ISSUE TITLE
Upload crahses only if the build is availale in hockey

### ISSUE THREAD

**Issue by sankartringapps** [bitstadium/HockeySDK-Android#240]
During the development, if a crash occurs hockey app sdk registers the crash in the hockey app without a build.

Can we have a method to control the crash upload only if the particular version is already uploaded to the hockey app?

**Comment by TroubleMakerBen** [comment]
Hey Sankar,

Thank you for getting in touch. I'm not sure if I understand your use-case correctly.
From what I understand, you don't want any crashes that happen during development, to end up on the HockeyApp portal, is that right?
If this is the case, we recommend that you wrap the `CrashManager.register(..)`-call with an if statement that checks either for build vs. release configs, or for an attached debugger, whatever fits your personal needs/preferences better. We currently don't have any plans to add a new API.

Feel free to reply here, get in touch in [our public slack](hockeycamp.slack.com) or open an issue in [our support](https://support.hockeyapp.net). =)

**Comment by sankartringapps** [comment]
You understand the use-case correctly. Will wrap it up with an if statement.

Thank you

**Comment by TroubleMakerBen** [comment]
You are welcome any time!

Best,
Benny
