### ISSUE TITLE
Device OS stays empty when sending events

### ISSUE THREAD

**Issue by galvanu** [bitstadium/HockeySDK-Android#245]
Hi, I'm using the SDK for metrics in Android widget.
I see that for some reason when I send events the device os property is empty.

I'm using the SDK in the following way:

MetricsManager.register(MyApp.getApplication(), "MY_APP_KEY");
MetricsManager.trackEvent("EventName", event);

Do I need to initialize anything else before sending events?
I do see that you have Device.java class under models but I can't find where it initializes all properties.

Any suggestions what should I do so it will be filled?

**Comment by TroubleMakerBen** [comment]
Hi Galvanu,

Thank you for getting in touch and apologies from our side for the rather slow response time. We don't officially support Android Widgets, so I guess the reason the OS doesn't show up is related to that. That said, we're looking into this, so stay tuned.

Thanks for using HockeyApp!

**Comment by MatkovIvan** [comment]
Hi @galvanu,

`AppWidgetProvider` is a `BroadcatReceiver`. Your process terminating between `onReceive` calls (all overridden methods from `AppWidgetProvider`). So, HockeyApp SDK cannot works correctly and as @TroubleMakerBen said, we don't support Android Widgets. Also I'm not sure that valid `Application` instance exists to pass to `MetricsManager.register`. Your `MyApp.getApplication()` is a just singleton right?

**Comment by TroubleMakerBen** [comment]
Hi @galvanu,
we've looked at adding Android Widget support. We won't support it anytime soon as we're very busy working on [Mobile Center](https://www.hockeyapp.net/mobile-center/about/).
That said, we'd happily accept a PR that adds this functionality.
