### ISSUE TITLE
java.net.UnknownHostException: Unable to resolve host "sdk.hockeyapp.net": No address associated with hostname

### ISSUE THREAD

**Issue by makingthematrix** [bitstadium/HockeySDK-Android#246]
Similar to #174  

HockeySDK 3.7.2
Samsung G900F
Android 6.0.1
 
The client experienced an internet connection failure. As far as I understand, it tried to report the error to HockeyApp, but HockeyApp crashed and that in turn caused Wire to crash. Might be difficult to reproduce.
#
[Wire_HockeyApp_UnknownHostException.log.zip](https://github.com/bitstadium/HockeySDK-Android/files/1038451/Wire_HockeyApp_UnknownHostException.log.zip)

**Comment by TroubleMakerBen** [comment]
Hey @makingthematrix,

thx for getting in touch. It looks like you are using a pretty old version of the SDK. We have improved a ton of things since then, can you upgrade HA to the latest version? 
If you continue to see this error again, please get in touch.

Thx,
Benjamin
