### ISSUE TITLE
Third attachment is not visible on feedback activity

### ISSUE THREAD

**Issue by sirekanyan** [bitstadium/HockeySDK-Android#261]
When 3 attachments were sent to server, third one isn't visible:

![photo_2017-07-04_17-06-26](https://user-images.githubusercontent.com/2663397/27833487-bf2c5972-60db-11e7-8a9b-dc3acac5e799.jpg)

**Comment by TroubleMakerBen** [comment]
Thank you for reporting this! We're fixing this in the next release.

Cheers!
Benny

**Comment by TroubleMakerBen** [comment]
This was included as a fix in the latest release. Closing this issue. =)
