### ISSUE TITLE
Ability to add more than 3 attachments to feedback

### ISSUE THREAD

**Issue by sirekanyan** [bitstadium/HockeySDK-Android#262]
Now there is only 3 attachments allowed. What do you think about if we made this number customizable?

**Comment by TroubleMakerBen** [comment]
Hey @sirekanyan,

Thank you for getting in touch. We currently don't have any plans to add the ability to customize the number of attachments per Feedback. This is more complicated than making a simple change to the SDK as it requires work on the backend and needs to be implemented on all platforms that support Feedback.
That said, we're of course fixing #261 . 

Thx for reporting that!

Benny
