### ISSUE TITLE
Support for 'Custom Events' in Android SDK?

### ISSUE THREAD

**Issue by adamtarmstrong** [bitstadium/HockeySDK-Android#267]
You iOS SDK GitHub ReadMe says, "You can now track Custom Events in your app, understand user actions and see the aggregates on the HockeyApp portal."

Are Custom Events also available in the Android SDK and the ReadMe has just not been updated?
Or are Custom Events not available in the Android SDK?

Thanks,
Adam.

**Comment by TroubleMakerBen** [comment]
Hey Adam,

Thanks for getting in touch. Yes, the Android SDK supports this feature, too. The Readme.md references our Knowledgebase (this is where we now host all of our docs). The article in question is [this one](https://support.hockeyapp.net/kb/client-integration-android/hockeyapp-for-android-sdk#user-metrics).

Let me know if you have more questions. Thanks for using HockeyApp!
Benny

**Comment by TroubleMakerBen** [comment]
Closing this issue as I answered the question. =)
