### ISSUE TITLE
Use of DEVICE_ID in SDK

### ISSUE THREAD

**Issue by jazzyjester** [bitstadium/HockeySDK-Android#270]
Hello, 
As tests of ecuretheorem.com, it found that our app that use hockeyapp sdk reading the DEVICE_ID.
They Wrote : 

> Discontinue the use of the ANDROID_ID in favor of the Android Advertising ID or a randomly generated ID.
> 
> The Advertising ID is a unique, resettable ID tied to the user for advertising purposes, and available via the Google Play Services. It gives users better controls as they can reset the ID or opt out, and provides developers with a simple, future-proof API to profile users for advertising purposes.

Do you plan to switch to Advertising ID in the future ?
Thanks.

**Comment by TroubleMakerBen** [comment]
Hey Ronny,

thx for getting in touch. We have an item on the backlog for this but I cannot give you an ETA for this.

Best,
Benny

**Comment by TroubleMakerBen** [comment]
As of HockeySDK 5.0.0-beta.1, we're no longer using `ANDROID_ID`. The SDK is generating a GUID which is not persisted across installations.

I'm keeping this issue open until 5.0.0 is no longer beta.

**Comment by TroubleMakerBen** [comment]
We just released HockeySDK 5.0.0, so I'm closing this.
