### ISSUE TITLE
Undeterminated update behavior on 5.0.0

### ISSUE THREAD

**Issue by yuriy-budiyev** [bitstadium/HockeySDK-Android#282]
Can't determinate wheter update fragment shown or activity launched.
I don't think that showing fragment in current activity is a good idea.

**Comment by yuriy-budiyev** [comment]
Activity doesn't start on tablet, but works fino on phone

**Comment by MatkovIvan** [comment]
Yes, this is what I told you about.
Dialog fragment was used on tablets instead of activity in previous versions as well.

**Comment by yuriy-budiyev** [comment]
Can I just start new activity always?

**Comment by MatkovIvan** [comment]
Currently not.

**Comment by yuriy-budiyev** [comment]
Please add that ability

**Comment by yuriy-budiyev** [comment]
Thank you, on older versions I forced activity by returning null from UpdateManagerListener#getUpdateFragmentClass()

**Comment by TroubleMakerBen** [comment]
We just released HockeySDK 5.0.0, so I'm closing this.
