### ISSUE TITLE
ProGuard Error on Version 5.0.0

### ISSUE THREAD

**Issue by FaridBeiranvand** [bitstadium/HockeySDK-Android#298]
Hi i Used Version 5.0.0:
`compile 'net.hockeyapp.android:HockeySDK:5.0.0'`
but When i want to use proGuard , it runs into this error:
`Warning:net.hockeyapp.android.utils.PermissionsUtil: can't find referenced method 'boolean canRequestPackageInstalls()' in library class android.content.pm.PackageManager
Warning:net.hockeyapp.android.utils.Util: can't find referenced method 'Notification$Builder(android.content.Context,java.lang.String)' in library class android.app.Notification$Builder
Warning:net.hockeyapp.android.utils.Util: can't find referenced class android.app.NotificationChannel
Warning:net.hockeyapp.android.utils.Util: can't find referenced method 'void createNotificationChannel(android.app.NotificationChannel)' in library class android.app.NotificationManager
Warning:net.hockeyapp.android.utils.Util: can't find referenced class android.app.NotificationChannel
Warning:there were 3 unresolved references to classes or interfaces.
Warning:there were 3 unresolved references to library class members.
Warning:Exception while processing task java.io.IOException: Please correct the above warnings first.`

please help me.thanks.

**Comment by MatkovIvan** [comment]
Hi @FaridBeiranvand 

These methods from the recent Android library. You need to update Android SDK or add ignore flag to ProGuard.

From [ProGuard manual](https://www.guardsquare.com/en/proguard/manual/troubleshooting#unresolvedlibraryclassmember):
>  If you're developing for Android and ProGuard complains that it can't find a method that is only available in a recent version of the Android run-time, you should change the build target in your project.properties file or build.gradle file to that recent version. You can still specify a different minSdkVersion and a different targetSdkVersion in your AndroidManifest.xml file.
Alternatively, you may get away with ignoring the inconsistency with the options -ignorewarnings or even -dontwarn.

**Comment by TroubleMakerBen** [comment]
Hey @FaridBeiranvand,

How are things? Were you able to resolve the issue?

I'd like to close the issue here if you have resolved it.

Cheers!

Benny

**Comment by FaridBeiranvand** [comment]
Hi.thanks a lot for your Complete solution.with using -dontwarn flag issue resovled.
