### ISSUE TITLE
Unable to grant permission for versions 5.0.0 or 5.0.1

### ISSUE THREAD

**Issue by hardekool** [bitstadium/HockeySDK-Android#301]
### Background:
The application has a dependency on ```net.hockeyapp.android:HockeySDK:5.0.1```.
The application requests permission to use ```Manifest.permission.WRITE_EXTERNAL_STORAGE```.

### Expected behaviour:
When permission is denied, dialogue is displayed prompting user to enable permission. The user must be able to grant permission, either through permission dialogue or manually through the Android App permissions activity.

### Current behaviour:
Permission is never granted even when manually enabling from the Android App permissions activity.

### To reproduce:
A [sample application](https://github.com/hardekool/permission_problem) exists exhibiting above mentioned behaviour. 
When the dependency on hockeySDK is removed from ```app/build.gradle```, the user is able to grant the permission.
Unable to reproduce the issue for release  ```net.hockeyapp.android:HockeySDK:4.1.5```

**Comment by MatkovIvan** [comment]
Hi @hardekool 
From release notes:
>  HockeySDK-Android now limits the WRITE_EXTERNAL_STORAGE permission with the maxSdkVersion filter. In some use cases, e.g. where an app contains a dependency that requires this permission, maxSdkVersion makes it impossible for those dependencies to grant or request the permission. The solution for those cases is to declare the tools:node="replace" manifest merging strategy later in the dependency tree:
`<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" tools:node="replace"/>`

Do you try this?

**Comment by hardekool** [comment]
@MatkovIvan , thank you for your quick response. This solved my problem. Classic RTFM issue :book:
