### ISSUE TITLE
storage permission

### ISSUE THREAD

**Issue by piyurabadiya** [bitstadium/HockeySDK-Android#319]
Hello All

After update version to 5.0.2
we have get new issue from your library 
here is issue ( Storage permission if already granted)
if remove your library my issues is resolved.

**Comment by MatkovIvan** [comment]
Hey @piyurabadiya 
Thanks for getting touch!

Could you please clarify what happened? The current description isn't enough to understand this.
What exactly issue do you have with the permission?

**Comment by piyurabadiya** [comment]
see below gif
Its perfect working in 4.0.2 and not work in 5.0.2

![20171016_141624](https://user-images.githubusercontent.com/5976724/31603303-573cb822-b27d-11e7-9572-c7bc558fc76e.gif)

**Comment by MatkovIvan** [comment]
Please note that `5.0.0` has changes related to that permission.

From [release notes](https://github.com/bitstadium/HockeySDK-Android/releases/tag/5.0.0):
> To be ready for Android O, HockeySDK-Android now limits the WRITE_EXTERNAL_STORAGE permission with the maxSdkVersion filter. In some use cases, e.g. where an app contains a dependency that requires this permission, maxSdkVersion makes it impossible for those dependencies to grant or request the permission. The solution for those cases is to declare the tools:node="replace" manifest merging strategy later in the dependency tree:
`<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" tools:node="replace"/>`

**Comment by piyurabadiya** [comment]
I am using below version in my project and I apply change according to your reply but still its not working properly .
      
compileSdkVersion 26
buildToolsVersion '26.0.2'

minSdkVersion 16
targetSdkVersion 26

**Comment by MatkovIvan** [comment]
Sorry to say, but I still don't have clear understanding your problem.
Could you please describe this in more detail?
-What exactly going wrong for comparing with expected behavior?
-How are you using HockeyApp SDK to do that feature? This match to latest documentation?
-Is there any useful information in the device logs?
-Is it reproduced on sample application or only on your main one?

**Comment by TroubleMakerBen** [comment]
Hey @piyurabadiya,
we'd love to help, can you please explain in more detail what issue you are running into?

Best,
Benjamin
