### ISSUE TITLE
Error: style attribute '@android:attr/windowEnterAnimation' not found

### ISSUE THREAD

**Issue by alexarraiza** [bitstadium/HockeySDK-Android#320]
Hi everyone

I get these errors when using HockeyApp 5.0.3 and gradle 3.0.0-rc2:

Error:(101, 5) error: style attribute '@android:attr/windowEnterAnimation' not found.
Error:(101, 5) error: style attribute '@android:attr/windowExitAnimation' not found.

on here:

$USER_FOLDER$/.gradle/caches/transforms-1/files-1.1/HockeySDK-5.0.3.aar/23150723a5962e9818263301f5e14033/res/values/values.xml

I'm also using Android Studio 3.0 RC 2, and I know it's not an stable version but I though you should know.

Thank you.

**Comment by TroubleMakerBen** [comment]
Hey Alex,

Thx for letting us know. We're working on this and will let you know as soon as it's fixed.

**Comment by bmourat** [comment]
Hi @alexarraiza 

I wasn't able to reproduce this issue with AS 3.0 rc2 and android Gradle plugin 3.0.0-rc2. 
I was wondering if this issue happens with new projects also? And also did you tried removing "@" sign when using those attributes, like this 'android:attr/windowEnterAnimation'?

Best,
Murat

**Comment by desteve** [comment]
Any advances or work around on this? I get the same error with AS 3.0 stable version and HockeyApp SDK 5.0.3. It's quite annoying because I can't build my project.

**Comment by bmourat** [comment]
Hi @desteve!

Please remove "@" signs from your style declarations like described here: https://stackoverflow.com/questions/45952607/error-style-attribute-androidattr-windowexitanimation-not-found
If that doesn't help, could you please provide a sample project to reproduce this issue?

Best,
Murat

**Comment by desteve** [comment]
Yes thanks. I was about to write that I've managed to solve the issue looking for these '@' signs and removing them. By the way, I found that the problem wasn't on the HockeyApp SDK but on an older library being included in my project, so I apologize for my complain.

Thanks again.

**Comment by TroubleMakerBen** [comment]
@desteve I'm glad that you were able to resolve the issue. Thx for using HockeyApp, you're awesome! Have a great week!
