### ISSUE TITLE
5.0.2 and 5.0.3 blocking write permissions?

### ISSUE THREAD

**Issue by Purup** [bitstadium/HockeySDK-Android#328]
Hey.

Been working on an app which needs to use the camera to take a picture and save it to a file. Have had problems with it denying me write permissions even though the user is prompted to allow them.

After many hours i found out that the only factor that had changed was upgrading to HockeyApp version 5.0.2 (Also tested with 5.0.3). I previously ran the much older 4.1.5, and when im using that everything works, camera opens, pictures gets saved to file.

I'll gladly try to explain more if you have any questions. I made a small sample project that uses the same code for the camera as the other project (I do apologize for the weird log statements).

https://github.com/Purup/CameraTest

Try removing or changing the HockeyApp version in the gradle file. (HockeyApp isn't used in the sample app)

**Comment by MatkovIvan** [comment]
Hi @Purup,
Thanks for getting in touch!

This is described in our [documentation](https://support.hockeyapp.net/kb/client-integration-android/hockeyapp-for-android-sdk#integrate-sdk) and [release notes](https://github.com/bitstadium/HockeySDK-Android/releases/tag/5.0.0):
> To be ready for Android O, HockeySDK-Android now limits the WRITE_EXTERNAL_STORAGE permission with the maxSdkVersion filter. In some use cases, e.g. where an app contains a dependency that requires this permission, maxSdkVersion makes it impossible for those dependencies to grant or request the permission. The solution for those cases is to declare the tools:node="replace" manifest merging strategy later in the dependency tree:
 `<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" tools:node="replace"/>`

Best,
Ivan

**Comment by Purup** [comment]
I guess i just need to read documentation better!

Thanks for the answer.

**Comment by MatkovIvan** [comment]
This issue is a duplicate of #301
