### ISSUE TITLE
Buttons are not fully displayed

### ISSUE THREAD

**Issue by vurf** [bitstadium/HockeySDK-Android#329]
Normal displayed
![uii9yg7o7y8](https://user-images.githubusercontent.com/10620593/32498750-8f8b2fae-c3e1-11e7-8255-a6e170127848.jpg)

Not normal. I'm override title first button that title was shortly, but third button is displayed
![_uchppszsiw](https://user-images.githubusercontent.com/10620593/32498770-a0e629c0-c3e1-11e7-83c9-2ec9d945f033.jpg)

**Comment by vurf** [comment]
As you see on first image - android 4.4.2, on second image - android 5.1. Maybe defect in android builder fragment. :(

**Comment by MatkovIvan** [comment]
Hi @vurf,

Unfortunately, this is a standard behavior of `android.app.AlertDialog` and marked as `Won't Fix` on [google issue tracker](https://issuetracker.google.com/issues/37008457).

You may override show dialog behavior using [`CrashManagerListener.onHandleAlertView`](https://github.com/bitstadium/HockeySDK-Android/blob/develop/hockeysdk/src/main/java/net/hockeyapp/android/CrashManagerListener.java#L142-L149). `android.support.v7.app.AlertDialog` doesn't have this problem but depend on support library, this is why it didn't use in HockeyApp out the box.

Best,
Ivan

**Comment by MatkovIvan** [comment]
Hi @vurf,

Unfortunately, this is a standard behavior of `android.app.AlertDialog` and marked as `Won't Fix` on [google issue tracker](https://issuetracker.google.com/issues/37008457).

You may override show dialog behavior using [`CrashManagerListener.onHandleAlertView`](https://github.com/bitstadium/HockeySDK-Android/blob/develop/hockeysdk/src/main/java/net/hockeyapp/android/CrashManagerListener.java#L142-L149). `android.support.v7.app.AlertDialog` doesn't have this problem but depend on support library, this is why it didn't use in HockeyApp out the box.

Best,
Ivan

**Comment by TroubleMakerBen** [comment]
Hey @vurf 

I just marked this issue as #wontfix and wanted to let you know why. The only reliable way to fix is º as @MatkovIvan explained – to introduce a dependency to the Android Support Library. 
This would be a) a breaking change and b) violates one of our core rules for the HockeySDK – which is to not have any or as little outside dependency.

I hope you understand and can override the dialog.

Best,
Benjamin

PS: if this becomes a more common issue (this is the first report of it so far), we might reconsider adding the dependency, so please keep your feedback coming!

**Comment by vurf** [comment]
@TroubleMakerBen ok, thanks :)
