### ISSUE TITLE
Unexpected `supportsRtl` attribute in AndroidManifest

### ISSUE THREAD

**Issue by smuldr** [bitstadium/HockeySDK-Android#334]
After updating to 5.0.4, our build failed with the following error:

```
Execution failed for task ':app:processDebugManifest'.
  > Manifest merger failed : Attribute application@supportsRtl value=(false) from AndroidManifest.xml:53:9-36
  is also present at [net.hockeyapp.android:HockeySDK:5.0.4] AndroidManifest.xml:18:18-44 value=(true).
  Suggestion: add 'tools:replace="android:supportsRtl"' to <application> element at AndroidManifest.xml:13:5-62:19 to override.
```

Applying the `tools:replace` attribute fixes the issue, but I don't think a third party library should be making decisions about wheter or not our app supports RTL layouts.

**Comment by TroubleMakerBen** [comment]
Hey!

Thx for filling this and for also making a PR for this!
We'll run a few tests on the PR and will merge as soon as that's done. The next release is probably gonna be in 2018 though.

Best,
Benjamin
