### ISSUE TITLE
Android Multidex Configuration,  Create file problem (Permission denied)

### ISSUE THREAD

**Issue by uc3po** [bitstadium/HockeySDK-Android#342]
Hi, 
I have an Android application with Multidex configuration. 
The hockey app is added to the gradle file. 
I have read and write permissions on my Android Manifest file. 
When I try to create a file I get the error "Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)". 
If I delete the Hockey App in the Gradle settings, I can create a file.

My grade configuration file:

apply plugin: 'com.android.application'

android {
    compileSdkVersion 27
    buildToolsVersion "27.0.2"
    defaultConfig {
        applicationId "com.tr.inaudio.studio"
        minSdkVersion 19
        targetSdkVersion 27
        versionCode 1
        versionName "1.0"
        multiDexEnabled true
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        manifestPlaceholders = [HOCKEYAPP_APP_ID: "My_Key"]
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    configurations.all {
        resolutionStrategy.force 'com.google.code.findbugs:jsr305:1.3.9'
    }

}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:multidex:1.0.1'
    compile 'com.android.support:appcompat-v7:27.0.0'
    compile 'com.android.support:design:27.0.0'
    compile 'com.android.support.constraint:constraint-layout:1.0.2'
    compile 'com.android.support:support-v4:27.0.0'
    compile 'com.google.android.gms:play-services-auth:11.4.2'
    compile 'com.google.android.gms:play-services-gcm:11.4.2'
    compile 'com.facebook.android:facebook-android-sdk:[4,5)'
    compile 'com.android.support:cardview-v7:27.0.0'
    compile 'com.miguelcatalan:materialsearchview:1.4.0'
    compile 'com.squareup.retrofit2:retrofit:2.3.0'
    compile 'com.squareup.retrofit2:converter-gson:2.3.0'
    compile 'com.squareup.okhttp3:okhttp:3.9.0'
    compile 'com.squareup.okhttp3:logging-interceptor:3.9.0'
    compile 'com.afollestad.material-dialogs:core:0.9.4.4'
    compile 'com.squareup.picasso:picasso:2.5.2'
    compile 'com.miguelcatalan:materialsearchview:1.4.0'
    compile 'de.hdodenhof:circleimageview:2.2.0'
    compile 'com.github.curioustechizen.android-ago:library:1.3.4'
    compile 'com.github.gabrielemariotti.cards:cardslib-core:2.1.0'
    compile 'com.github.gabrielemariotti.cards:cardslib-cards:2.1.0'
    compile 'com.github.gabrielemariotti.cards:cardslib-recyclerview:2.1.0'
    compile 'com.github.gabrielemariotti.cards:cardslib-extra-staggeredgrid:2.1.0'
    compile 'com.github.gabrielemariotti.cards:cardslib-extra-dragdrop:2.1.0'
    compile 'com.github.Cutta:TagView:1.3'
    compile 'com.github.bumptech.glide:glide:4.2.0'
    compile 'com.google.guava:guava:23.2-android'
    compile 'joda-time:joda-time:2.7'
    compile 'com.amazonaws:aws-android-sdk-s3:2.6.+'
    //    compile 'net.hockeyapp.android:HockeySDK:5.0.3'

    compile group: 'com.cloudinary', name: 'cloudinary-android', version: '1.20.0'
    testCompile 'junit:junit:4.12'

    annotationProcessor 'com.github.bumptech.glide:compiler:4.2.0'
}

apply plugin: 'com.google.gms.google-services'

**Comment by MatkovIvan** [comment]
Hi @uc3po 

I guess this is related to manifest merging.
This is described in our [documentation](https://support.hockeyapp.net/kb/client-integration-android/hockeyapp-for-android-sdk#integrate-sdk) and [release notes](https://github.com/bitstadium/HockeySDK-Android/releases/tag/5.0.0):
> To be ready for Android O, HockeySDK-Android now limits the WRITE_EXTERNAL_STORAGE permission with the maxSdkVersion filter. In some use cases, e.g. where an app contains a dependency that requires this permission, maxSdkVersion makes it impossible for those dependencies to grant or request the permission. The solution for those cases is to declare the tools:node="replace" manifest merging strategy later in the dependency tree:
 `<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" tools:node="replace"/>`

Let me know if it doesn't help you.

Best,
Ivan

**Comment by uc3po** [comment]
It works. Thanks.

**Comment by MatkovIvan** [comment]
This issue is a duplicate of #301

**Comment by 3mph4515** [comment]
Knowing how short is a list of people who read the changelog, this decision to set maxSdkVersion look a little bit risky.

**Comment by TroubleMakerBen** [comment]
@3mph4515 We've debated this quite a bit and you are absolutely right that only few people read changelogs. That said, it's the solution that we chose to use and we need to stick with it for the time being.
