### ISSUE TITLE
5.0.4 affects the app's WRITE_EXTERNAL_STORAGE permission

### ISSUE THREAD

**Issue by kmspop** [bitstadium/HockeySDK-Android#344]
Hi.

I have noticed, with the latest 5.0.4, our app's WRITE_EXTERNAL_STORAGE gets FUBARed.
Writing a file to the external storage stopped working after upgrading to SDK 5.0.4.
File::mkdirs() and File::exists() both were returning false. No specific exceptions were thrown but seemed like a permission issue.
Went to the settings, opened the application manager, and saw the app's permission list.
Under permission list, I could only see "read the contents of your SD card", and "modify or delete the contents of your SD card" was not there anymore.
Verified AndroidManifest has both read and write permission specified.

    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />

Switched back to SDK 4.1.4 which I've been using, and I verified "modify or delete the contents of your SD card" came back, and our app started to function again.

This is our project gradle config.
    compileSdkVersion 22
    buildToolsVersion '25.0.3'
    defaultConfig {
        applicationId "blah"
        minSdkVersion 16
        targetSdkVersion 19
        versionCode xxx
        versionName "x.x.xx"
        // Enabling multidex support.
        multiDexEnabled true
    }

Tested Devices
Samsung SM-P600 (Android 5.1.1)
Samsung S7 Edge (Android 7.0)

**Comment by MatkovIvan** [comment]
Duplicate of #301

**Comment by MatkovIvan** [comment]
Hi @kmspop,

This is described in our [documentation](https://support.hockeyapp.net/kb/client-integration-android/hockeyapp-for-android-sdk#integrate-sdk) and [release notes](https://github.com/bitstadium/HockeySDK-Android/releases/tag/5.0.0):
> To be ready for Android O, HockeySDK-Android now limits the WRITE_EXTERNAL_STORAGE permission with the maxSdkVersion filter. In some use cases, e.g. where an app contains a dependency that requires this permission, maxSdkVersion makes it impossible for those dependencies to grant or request the permission. The solution for those cases is to declare the tools:node="replace" manifest merging strategy later in the dependency tree:
 `<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" tools:node="replace"/>`

Let me know if it doesn't help you.

Best,
Ivan

**Comment by kmspop** [comment]
Thank you for a quick reply.
It all makes sense.
