### ISSUE TITLE
UpdateManager breaks on Android O

### ISSUE THREAD

**Issue by ReneFerrari** [bitstadium/HockeySDK-Android#345]
I have implemented the update mechanism in my App and it works perfectly fine. 
Today I tried it on a Nexus 6P with Android 8.1.1. The way I did it was that I downloaded an earlier version of the App, with the hope that upon App start I get prompted to update it (Note I have tried this on Android L, Android M, Android N before), which fortunately I was. I clicked on update, the download started finished but that was it. Still was on the old App version and every App start I got prompted to update. So I thought to myself maybe its an issue with this specific smartphone. 

I went on tried it in the Emulator with SDK 27 (identified as Android null :D) and SDK 26. Unfortunately I did not even get a dialog prompting me to update the App. Fortunately this was also the case for SDK 22 therefore I think its an issue with the Emulator itself.

I went on and tried it on my OnePlus 5 (Android 7.1) and there it worked normally. Updated it to Android 8.0 tried it again didn't work anymore. It looks like I sucessfully downloaded the updated version (Progressbar on Dialog reaches 100%) but I am stuck at the update screen. Restarting the App won't help either.

It is really desperating :/. I know that Android O does not have a big market share at all but in a few months we will see many devices with it.

Hope it will be fixed soon and thanks for the otherwise flawlessly and easily integrateable SDK :)

**Update:** The new Version of the App is visible in the "Downloads" folder and can be installed manually from there.

**Update 2:** Just checked and I am using an older Version of the SDK... I will check it later / tomorrow if the Problem still exists with the current version. Hope thats the problem. Will update the post then!

**Update 3:** After upgrading to the current version of the SDK I don't even see any dialog that lets me select to update, although onUpdateAvailable in the UpdateManagerListener gets called. I'll dig into this further tomorrow (haven't tested it on a below Android O device yet, though updating the App is probably still possible)

**Comment by TroubleMakerBen** [comment]
Hi Rene,

which version of the HockeySDK are you using. Assuming you are using HockeySDK 5, that there's an important change related to Updates and the permission to write to external storage?
To quote our release notes:

This is described in our [documentation](https://support.hockeyapp.net/kb/client-integration-android/hockeyapp-for-android-sdk#integrate-sdk) and [release notes](This is described in our [documentation](https://support.hockeyapp.net/kb/client-integration-android/hockeyapp-for-android-sdk#integrate-sdk) and [release notes](https://github.com/bitstadium/HockeySDK-Android/releases/tag/5.0.0):
> To be ready for Android O, HockeySDK-Android now limits the ``WRITE_EXTERNAL_STORAGE permission with the `maxSdkVersion` filter. In some use cases, e.g. where an app contains a dependency that requires this permission, `maxSdkVersion` makes it impossible for those dependencies to grant or request the permission. The solution for those cases is to declare the tools:node="replace" manifest merging strategy later in the dependency tree:
 `<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" tools:node="replace"/>`

Thx for using HockeyApp and let me know if this helps!

Best,
Benjamin

**Comment by ReneFerrari** [comment]
Hi Ben!

I use the latest build. Fortunately your solution (adding `tools:node="replace"`) as described in the links you shared me solved my issue. 

I am sorry that I hadn't checked out the changelog / hadn't read the whole documentation which I will always do in the future if I encounter any problem.

Anyway thanks for your fast reply!
(issue can be closed)

Have a nice day,
Rene

**Comment by TroubleMakerBen** [comment]
Rene,

no worries. This comes up at least once a month but I haven't found a better way how to point this out. If you have a suggestion, please let me know ;)

Cheers!
Benjamin

**Comment by ReneFerrari** [comment]
Hi Benjamin!

Maybe writing about it in the readme file would help. After: "You can even force the installation of certain updates." I would just append: "**To support Android O devices please our [documentation](https://support.hockeyapp.net/kb/client-integration-android/hockeyapp-for-android-sdk#integrate-sdk) and [release notes](https://github.com/bitstadium/HockeySDK-Android/releases/tag/5.0.0)**"

I think that when something is not working as intended, the first document you are going to check is the readme (at least I always do that), because everything important is written consizely in it. I would also keep the sentence bold - with more and more Android O devices on coming to the market a lot more people are probably going to get this issue (if they have not read the release notes / documentation ;D). 

I hope this helps!

Rene

**Comment by TroubleMakerBen** [comment]
@ReneFerrari I see. We'll talk about it. We definitely need more visibility for it. Thx for the input! =)
