### ISSUE TITLE
Hockey app can not upload apk

### ISSUE THREAD

**Issue by mengdd** [bitstadium/HockeySDK-Android#352]
Hi, team, I found my project suddenly cannot upload apk by fastlane... came our app not found error
then I use curl to have a try

so I use curl to have a try 

```
curl \
  -F "status=2" \
  -F "notify=1" \
  -F "notes=Test Hockey upload" \
  -F "notes_type=0" \
  -F "ipa=@xxx.apk" \
  -H "X-HockeyAppToken: token" \
  https://rink.hockeyapp.net/api/2/apps/app-id/app_versions/upload
```

it came out the same error { app:{not found}}

Do someone know the reason?

**Comment by TroubleMakerBen** [comment]
Hey @mengdd,

can you get in touch via [Support](https://support.hockeyapp.net)? We might need your app id for that and you probably don't want to share this here.

I'll close this issue here.

Best,
Benjamin

**Comment by tashpemhiwa** [comment]
[How] was this issue resolved?

**Comment by TroubleMakerBen** [comment]
@tashpemhiwa Unfortunately, can't find any info in our support that they got in touch with us. We are currently not aware of any issues. Can you please get in touch via support?

**Comment by mengdd** [comment]
@tashpemhiwa Hi, I remember the issue is due to wrong api key I used.

**Comment by tashpemhiwa** [comment]
@mengdd, @TroubleMakeBen, thanks for the responses.
