### ISSUE TITLE
Email authentication issue or misunderstanding

### ISSUE THREAD

**Issue by XabierGoros** [bitstadium/HockeySDK-Android#354]
I'm a little bit confused of how the `LoginManager.LOGIN_MODE_EMAIL_ONLY` authentication mode works. If I set the `LoginManager.LOGIN_MODE_EMAIL_PASSWORD` option and I enter my HockeyApp email and password the request is performed and further calls to check updates works as expected. However, if I use the email only I always get:

```
{
    "status": "invalid"
}
```

So, what do I do wrong or what I misunderstanding from your [docs](https://support.hockeyapp.net/kb/client-integration-android/authenticating-users-on-android)? Could you guys help to understand that authentication mode?

Thanks a lot in advance
     
**Information**
Android HockeyAppSDK: 5.1.0

**Comment by bmourat** [comment]
Hey @XabierGoros 

What register method of LoginManager you are using? Could you provide code snippet?

**Comment by XabierGoros** [comment]
Sure

```
  fun login(activity: Activity) {
    try {
      val ai = activity.packageManager.getApplicationInfo(activity.packageName,
          PackageManager.GET_META_DATA)
      val bundle = ai.metaData
      val hockeyAppId = bundle.getString("net.hockeyapp.android.appIdentifier")
      LoginManager.register(activity, hockeyAppId, LoginManager.LOGIN_MODE_EMAIL_ONLY)
      LoginManager.verifyLogin(activity, activity.intent)
    } catch (e: PackageManager.NameNotFoundException) {
      Log.e("", "Failed to load meta-data, NameNotFound: " + e.message)
    } catch (e: NullPointerException) {
      Log.e("", "Failed to load meta-data, NullPointer: " + e.message)
    } catch (e: Exception) {
      Log.e("", "Failed to load meta-data, Exception: " +  e.message)
    }
  }
```

**Comment by bmourat** [comment]
When using LOGIN_MODE_EMAIL_ONLY you should use your appSecret, not your appIdentifier.

**Comment by XabierGoros** [comment]
Oh thanks, I got confused by the overloaded parameter, and also because with email/pass works with the `appIdentifier`.

How sensitive is the `appSecret`? Is it alright if it's hard-coded in the app like the `appIdentifier`?

**Comment by TroubleMakerBen** [comment]
Hey @XabierGoros,

You probably don't want to put this in your repo/hard-code as it can is used to restrict usage of your app, but some people still do it.

Best,
Benjamin
