### ISSUE TITLE
DownloadFileTask using unsecure HttpUrlConnection

### ISSUE THREAD

**Issue by LittleHuba** [bitstadium/HockeySDK-Android#358]
APK files are downloaded from a provided url with 6 redirects wherever they are going to. No checks if the file is even the proper APK nor if it has been tampered with. This is such a huge security issue, it compromises the whole system!

You should fix this ASAP!!!

**Comment by LittleHuba** [comment]
Metrics are also being sent over unencrypted connections, essentially giving user information to the www for free. Feedback is also sent unecrypted via http... AttachmentDownloader does the same.

Currently this SDK is one big security-breach!!!

**Comment by MatkovIvan** [comment]
Hi @LittleHuba 

We use `https` for **all** requests. If you read [﻿Security with HTTPS and SSL](https://developer.android.com/training/articles/security-ssl.html) and [HttpURLConnection](https://developer.android.com/reference/java/net/HttpURLConnection.html) android documents, you can find that:
> Calling `openConnection()` on a URL with the "https" scheme will return an `HttpsURLConnection`

In the same docs you can find that `javax.net.ssl.HttpsURLConnection` class extends `java.net.HttpURLConnection`. So, variables of type `HttpUrlConnection` in our code doesn't mean that data will send unencrypted.

Best,
Ivan

**Comment by LittleHuba** [comment]
Hi Ivan,
sorry that is my bad then. I got about 10 red flags in various security checks, since you are not enforcing HTTPS by using HttpsURLConnection.

Still the problem with referring stands and additionally there is no check if the downloaded APK is the one wanted. You could for example check the signature or at least the package name. The dialogs Android provides at installation only verify the Icon and the app name. You should at least restrict the hosts from where downloading is allowed. Else a simple DNS chache attack could break the whole update system.

**Comment by TroubleMakerBen** [comment]
Hey @LittleHuba,

thx for getting in touch. We're talking about this issue over her.
I'd like to know more about your use-case as you are the first person in 7 years of HockeyApp to bring up this concern. Feel free to shoot me an email to bereimol @ myemployer . com

Best,
Benjamin

**Comment by LittleHuba** [comment]
Hi @TroubleMakerBen,
I'm unable to write you a mail. My mailserver respons with "Connection timed out". But as there is no sensitive information in the mail anyway, I'll just post it here:

Firstly I do not really understand why there is a need for a specific use case to require a soundproof distribution system. As far as I know there are many cases of security breaches by taking over the updating system. But to give you a use case that could lead to huge problems:
Assume I’m building an app that will be delivered to employees of a big company, specifically to smartphones distributed by the company. These smartphones have sensitive data on them (internal mails, …) which can severely damage the business of the company. 
By compromising your system, let’s say with a DNS cache attack, the attacker could install a rootkit on the smartphone and make all this internal data public. Additionally he could fake the name and the icon of the original app and thereby install the rootkit without knowledge of the user. Using a different package name, the original software would still reside on the smartphone and further updates would throw no error. Thereby he would have silently taken over the phone and nobody would be the wiser.

Hope this helps!

**Comment by TroubleMakerBen** [comment]
Hi @LittleHuba,

I understand the scenario you are describing. I was more thinking along the lines of "@LittleHuba has customer requirements that call out this as a issue".

Thx for sharing. I will raise this topic with our PMs.

Best,
Benjamin
