### ISSUE TITLE
Registering CrashManager on Application OnStart

### ISSUE THREAD

**Issue by opcodewriter** [bitstadium/HockeySDK-Android#360]
Is registering CrashManager on Application `OnStart` a supported scenario?
I am providing my own `CrashManagerListener` where I override `shouldAutoUploadCrashes()` and return true.

The reason for this is to be able to send crash logs if app crashes on OnActivity OnStart. It's not clear to me how am I supposed to implement this scenario. So I figured I need to initialize CrashManagerListener on the Application OnStart.

The issue I see is the app stays blocked now on the splash screen.

**Comment by MatkovIvan** [comment]
Hi @opcodewriter,

Thanks for getting in touch.
By the names of methods, I suspect this is related to Xamarin SDK, right?

Best,
Ivan

**Comment by opcodewriter** [comment]
Correct

**Comment by opcodewriter** [comment]
More info:
I'm purposely crashing the app by throwing an exception at the end of Activity:OnStart. I want to handle the scenario when Activity crashes on Acvitity OnStart.

Looking at the logcat, the reason why it appears the app stays blocked on the splash screen is because the application is actually in a crash-restart loop. It's crashing and restarting indefinitely.
If I remove the call `HockeyApp.Android.CrashManager.Register(...)` the loop doesn't happen, the app crashes and I see the system dialog "XXX has stopped. Close app"

**Comment by TroubleMakerBen** [comment]
Hey @opcodewriter,

Your trying to solve one of the trickiest cases in crash reporting – crashes that happen early in the app's lifecycle. Keep that in mind.

> Why is HockeyApp restarting the app on crash?
HockeyApp SDK doesn't contain any logic to restart the app on a crash. Without access to you source, I have no explanation for this behavior. I tried to repro it just for kicks and I can't repro this at all.

> If I remove the call HockeyApp.Android.CrashManager.Register(...) the loop doesn't happen, the app crashes and I only see the system dialog "XXX has stopped. Close app", which is expected.

What makes sense is that the app is "stuck" in a crash-loop as  you are launching, crashing and restarting the application again, crash it again, in an endless loop. But HockeyApp isn't involved in restarting the app.

Overall what you are trying to do is hard to achieve with the SDK. I think it's doable but I don't have an example ready.
Please check out [our javadoc](https://www.hockeyapp.net/help/sdk/android/5.1.0/index.html) for `CrashManagerListener` first.
What you typically want to do is implement `onNewCrashesFound()`, and maybe store a flag or trigger a control flow that's different from your regular control flow if there are crashes.
You can then implement the other callbacks (e.g. `onCrashesSent()`) to get notified once the SDK is done sending crashes and show your typical UI.

Best,
Benjamin

**Comment by TroubleMakerBen** [comment]
Hi,
we haven't heard from you in a long time, so I'm closing this issue. Please reopen it in case you run into this issue again and feel free to get in touch through [support](https://support.hockeyapp.net).
