### ISSUE TITLE
HockeyUpdate: No Update Info available

### ISSUE THREAD

**Issue by finkbit** [bitstadium/HockeySDK-Android#363]
I have followed the SDK setup documentation for android but I cannot get UpdateManager to show a dialog when a new version of my app is available.

I have correctly incremented the version and it displays accordingly in the HockeyApp dashboard. I also ticked the "Mandatory Update" radio button on my version(s). Here are the methods I have inside my MainActivity.

onCreate
```
@Override
protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    HockeyLog.setLogLevel(Log.VERBOSE);
    SplashScreen.show(this);
    checkForUpdates();
}
```

checkForUpdates
```
private void checkForUpdates() {
    UpdateManager.register(this);
}
```

unregisterManagers
```
private void unregisterManagers() {
    UpdateManager.unregister();
}
```

onDestroy
```
@Override
public void onDestroy() {
    super.onDestroy();
    unregisterManagers();
}
```

My devices get recorded in the dashboard successful with my SDK version (5.1.0). I set the log level to "VERBOSE" to see if I could see anything out of the ordinary. The one and only log I receive in adb logcat is `03-07 15:53:41.560 10257 10257 V HockeyUpdate: No Update Info available`.

This message is kind of vague I'm not sure where to go from here. Any help is appreciated.

**Comment by dhei** [comment]
Hey @finkbit,

I noticed `SplashScreen.show(this)` is called in your `onCreate()` method. If `SplashScreen.show(this)` creates a new android activity, then it might be problematic because `onDestroy()` method which unregister the update manager is going to be called upon the creation of new activity. If that is the case, `checkForUpdate()` won't work as update manager is already unregistered.

The other possible cause of the problem is the android `WRITE_EXTERNAL_STORAGE` permission. Starting from HockeySDK Android v5.0.0, described in our [documentation](https://support.hockeyapp.net/kb/client-integration-android/hockeyapp-for-android-sdk#integrate-sdk) and [release notes](https://github.com/bitstadium/HockeySDK-Android/releases/tag/5.0.0):

> To be ready for Android O, HockeySDK-Android now limits the WRITE_EXTERNAL_STORAGE permission with the maxSdkVersion filter. In some use cases, e.g. where an app contains a dependency that requires this permission, maxSdkVersion makes it impossible for those dependencies to grant or request the permission. The solution for those cases is to declare the tools:node="replace" manifest merging strategy later in the dependency tree:
> `<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" tools:node="replace"/>`

**Comment by finkbit** [comment]
Hi @dhei thanks for the reply!

I suspected that too, so I also tried it without the `SplashScreen.show(this)` but I'm experiencing the same behavior. I also tried that workaround for WRITE_EXTERNAL_STORAGE to no avail.

I'm also using `react-native`. We have this working on iOS without issue. 

Thanks,
finkbit

**Comment by finkbit** [comment]
It does look like the update manager is being successfully registered because I'm seeing output from logcat. But the message is `HockeyUpdate: No Update Info available`.

I've tried all the suggestions where do I go from here? 😢

**Comment by finkbit** [comment]
Okay so I'm still having an issue but I'm getting a little further. I changed my check for updates method a little bit.

```
    private void checkForUpdates() {
        UpdateManager.register(this, getResources().getString(R.string.hockeyapp_app_id), new 
            UpdateManagerListener() {
                @Override
                public void onNoUpdateAvailable() {
                    super.onNoUpdateAvailable();
                    Log.d("noUpdateAvailable", "no update available.");
                }

                @Override
                public void onUpdateAvailable(JSONArray data, String url) {
                    super.onUpdateAvailable(data, url);
                    Log.d("onUpdateAvailable", url);
                }
            }, true);
        }
```

**onNoUpdateAvailable()** IS getting called but **onUpdateAvailable()** is never called even though their is a new version available. What could be causing this?

**Comment by finkbit** [comment]
We're just going to use the Play Store & TestFlight.

Thanks,
finkbit

**Comment by elamalani** [comment]
@finkbit I see that you closed this issue but I wanted to mention that HockeyApp doesn't support React Native SDK. [App Center ](https://appcenter.ms) is the next generation of HockeyApp and we support React Native platform in App Center if you'd like to use that for your application.
