### ISSUE TITLE
Android/Device Id Inconsistency

### ISSUE THREAD

**Issue by rspopovi** [bitstadium/HockeySDK-Android#364]
The Device Id registered for downloads does not match the Device Id registered for installations:

Download:
![image](https://user-images.githubusercontent.com/30935127/37298176-02f4abfc-25f6-11e8-89c1-2abe3d64e84c.png)

Installation:
![image](https://user-images.githubusercontent.com/30935127/37298245-291397b2-25f6-11e8-8dff-64cfa1601f59.png)

These are all the same device which I have been using to try to configure and test the UpdateManager, with no luck, and I believe this is why.

SDK Version: HockeySDK.Xamarin v5.1.2
Android 7.1.1
Samsung Galaxy Tab A

**Comment by jaelim-ms** [comment]
Can you explain what is your exact problem?

**Comment by rspopovi** [comment]
Closing this because it is a duplicate of this issue:
https://github.com/bitstadium/HockeySDK-Android/issues/350
