### ISSUE TITLE
Attachment file for crash

### ISSUE THREAD

**Issue by molnarr2** [bitstadium/HockeySDK-Android#365]
iOS has the ability to attach a file to the crash log whereas Android does not. I've implemented it to submit the file via the `HttpURLConnectionBuilder.writeMultipartData()` function and it will not show up within the HockeyApp crash. Verified the data was sent correct by a PHP script and also have the iOS side working. Android is using 'attachment0' as the fieldname. Does HockeyApp web site not show Android attachment files? When I get this working was planning on submitting a pull request for the change.

**Comment by elamalani** [comment]
@molnarr2 HockeyApp site has an option to show attachment file for a crash report. You can click on Crashes -> Crash Group -> Crash logs, there is a "Data" section below and when you click on "Meta" tab under it, you should see the data attached.

**Comment by molnarr2** [comment]
@elamalani So I compared what iOS is doing to Android via their HTTP request yet Android will not show up the attachment file on HockeyApp site. iOS works fine with showing up the attachment file. 

Here is a dump between iOS and Android of the HTTP request. 

[Dump.zip](https://github.com/bitstadium/HockeySDK-Android/files/1835360/Dump.zip)

Obviously there are differences in the way iOS and Android submits their crash reports. Does the backend for HockeyApp not accept an `attachment0` for Android or does Android need to submit it's crash like iOS using the `xml` attachment?
