### ISSUE TITLE
Pause updates on certain screens?

### ISSUE THREAD

**Issue by alizahid** [bitstadium/HockeySDK-Android#366]
Is there any way I can pause updates on certain screens?

Here's how I'm thinking it'll go down.

- I register `UpdateManager` in `MainActivity` (or wherever)
- When the results are fetched, before showing a dialog, it checks for some boolean
- If boolean is `false`, don't show the dialog
- Once the boolean becomes `true`, trigger update again

Here's what I've tried

- Register
- When it goes to a certain screen, I unregister

But by then, the dialog has already popped. Any workaround?

**Comment by MatkovIvan** [comment]
Hi @alizahid

Thanks for getting in touch.
You can pass `false` to `isDialogRequired` parameter when you call [UpdateManager.register](https://github.com/bitstadium/HockeySDK-Android/blob/5.1.0/hockeysdk/src/main/java/net/hockeyapp/android/UpdateManager.java#L90-L98) to prevent dialog showing. Then, you can use [UpdateManagerListener.onUpdateAvailable](https://github.com/bitstadium/HockeySDK-Android/blob/5.1.0/hockeysdk/src/main/java/net/hockeyapp/android/UpdateManagerListener.java#L74-L80) to implement any custom behaviour.

Best,
Ivan

**Comment by TroubleMakerBen** [comment]
Hi,
we haven't heard from you in a while so I'm closing this issue. 
Please reopen this issue if you have additional comments.
