### ISSUE TITLE
Stack trace is empty

### ISSUE THREAD

**Issue by xtyz** [bitstadium/HockeySDK-Android#371]
Stack trace is empty in hockeayapp (https://rink.hockeyapp.net) after obfuscation (Proguard). 

> Stacktrace cannot be displayed.

Android default logger show obfuscated  error correctly in Logcat. 
Version 5.1.0

**Comment by TroubleMakerBen** [comment]
Hi @xtyz,

is this still an issue? Have you uploaded the mapping file?
