### ISSUE TITLE
Equivalent iOS' isCrashManagerDisabled for Android

### ISSUE THREAD

**Issue by thuytrinh** [bitstadium/HockeySDK-Android#374]
Firstly, thanks for this cool library which helps us a lot. We're implementing some sort of GDPR feature which allows users to opt-out sending app crashes to HockeyApp. On iOS, there's `isCrashManagerDisabled` to achieve this:

```swift
BITHockeyManager.shared().configureWithIdentifier("APP_IDENTIFIER")
BITHockeyManager.shared().isCrashManagerDisabled = true
BITHockeyManager.shared().startManager()
```

I'm wondering whether there's such equivalent API for Android? If there isn't, quite sad but there's any way to workaround it? I found https://github.com/bitstadium/HockeySDK-Android/issues/65 but the thread is quite old since 2015.

Thank you very much.

**Comment by MatkovIvan** [comment]
Hi @thuytrinh 

Thanks for getting in touch.
For Android, you can simply not call `CrashManager.register` if you don't need it.

Best,
Ivan
