### ISSUE TITLE
updated apk files are remained

### ISSUE THREAD

**Issue by YoungjaeKim** [bitstadium/HockeySDK-Android#376]
I found that updated apk files are in download directory.
Below code is what I did in my project.

It would be good to remove previous ones, or provide `RemoveDownloaded` option to `UpdateManager`.

```java
private void removeUpdateApk() {
    File externalFileDir = getExternalFilesDir(Environment.DIRECTORY_DOWNLOADS);
    File[] apkList = externalFileDir.listFiles(new FilenameFilter() {
        @Override
        public boolean accept(File dir, String name) {
            return name.endsWith(".apk");
        }
    });
    for(File file : apkList) {
        file.delete();
    }
}  
```

**Comment by TroubleMakerBen** [comment]
Hi @YoungjaeKim,

this is a known issue but I cannot provide you with an ETA for this as we're working on making [App Center](https://appcenter.ms) awesome.
In fact, the App Center SDK behaves differently and cleans up app updates.

Please get in touch if you have further questions.
