### ISSUE TITLE
Crash in Hockey: Thread starting during runtime shutdown

### ISSUE THREAD

**Issue by johnryan** [bitstadium/HockeySDK-Android#383]
A little bit meta seeing a crash in hockey code via a hockey crash report:

```
Version Code: 1633
Version Name: 2.4.3
Android: 8.0.0
Android Build: R16NW.G930VVRU4CRE5
Manufacturer: samsung
Model: SM-G930V
Thread: HockeyApp User Metrics Sender Queue-10222
CrashReporter Key: 876c913e-a6da-4060-ac78-1f2a9fd9dced
Start Date: 2018-07-08T17:55:36.703Z
Date: 2018-07-08T18:55:54.317Z

java.lang.InternalError: Thread starting during runtime shutdown
	at java.lang.Thread.nativeCreate(Thread.java)
	at java.lang.Thread.start(Thread.java:733)
	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:970)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1377)
	at android.os.AsyncTask.executeOnExecutor(AsyncTask.java:651)
	at net.hockeyapp.android.utils.AsyncTaskUtils.execute(AsyncTaskUtils.java:21)
	at net.hockeyapp.android.metrics.Sender.triggerSending(Sender.java:82)
	at net.hockeyapp.android.metrics.Persistence.persist(Persistence.java:95)
	at net.hockeyapp.android.metrics.Channel.synchronize(Channel.java:123)
	at net.hockeyapp.android.metrics.Channel$SynchronizeChannelTask.run(Channel.java:215)
	at java.util.TimerThread.mainLoop(TimerThread.java:555)
	at java.util.TimerThread.run(TimerThread.java:505)
```

**Comment by TroubleMakerBen** [comment]
Hi Ryan,

thx for getting in touch and sorry about this. Which SDK version are you using? Can you share the setup code with us? Have you been able to reproduce the issue?
Apologies for the many questions but we need this info to investigate this issue.

PS: if you don't feel comfortable sharing your setup code here, please get in touch through https://support.hockeyapp.net and mention this issue in the ticket.

**Comment by johnryan** [comment]
@TroubleMakerBen thanks for the response. I have not been able to reproduce and it has only happened a few times. From what I can tell it's caused by code being executed while the application is shutting down but I was just investigating since that's what crash reports are for ;)

SDK: 5.1.0

Setup Code:
```
        CrashManagerListener crashListener = new CrashManagerListener() {
            @Override
            public void onNewCrashesFound() {
                super.onNewCrashesFound();
                AnalyticsManager.trackEvent("Mobile App Crash", null);
            }

            @Override
            public boolean shouldAutoUploadCrashes() {
               return true;
            }


            @Override
            public boolean ignoreDefaultHandler() {
                return super.ignoreDefaultHandler();
            }

            @Override
            public String getDescription() {
                return mFileLogger.getFileLogStringLimitedToSize(5000);
            }

            @Override
            public String getContact(){

                String email = null;
                Realm realm = Realm.getDefaultInstance();
                User user = UserStore.getCurrentUser(realm);
                if (user != null){
                    email = user.getEmail();
                }
                realm.close();

                return email;
            }

        };

        CrashManager.register(this, HOCKEY_APP_ID, crashListener);
        MetricsManager.register(this, HOCKEY_APP_ID);
```

**Comment by TroubleMakerBen** [comment]
Cool, thx for this! We'll update this issue accordingly.

**Comment by TroubleMakerBen** [comment]
Hey @johnryan,

@MatkovIvan and I chatted about this today. We were debating catching the exception but doing this for a `java.lang.InternalError` doesn't look like the right thing. At this point we're not aware of anything we can do to prevent the issue, after all, the runtime is shutting down.

I'm keeping this issue for now and tag it as "wontfix" but please keep us posted if this happens more often. And of course, feel free to comment.

Cheers!
Benjamin

**Comment by johnryan** [comment]
@TroubleMakerBen okay thanks...yeah there aren't a lot of these errors (and i've seen similar `Thread starting during runtime shutdown` errors over the years) but i'll keep an eye on it. As far as you guys can tell is my analysis of the stack trace correct? i.e. that it's caused by executing code while the app is quitting / phone is shutting down etc?

**Comment by TroubleMakerBen** [comment]
Exactly, the Android runtime is shutting down, which means the device is shutting down and the HockeyApp SDK starts triggers an async call (`net.hockeyapp.android.metrics.Sender.triggerSending(Sender.java:82) etc. etc.` right at this moment.

Thx for keeping an eye out for us! You rock!

**Comment by TroubleMakerBen** [comment]
Hey,
we haven't heard about this in the past two months so I'm closing this issue. Please comment or reopen in case this becomes a problem again.

Cheers!
Ben
