### ISSUE TITLE
Initial User Subject ignored when passed in bundle

### ISSUE THREAD

**Issue by vandert** [bitstadium/HockeySDK-Android#388]
My goal is to provide a default subject for the user in the FeedbackActivity.  Based the FeedbackManager code, it appears the value for InitialUserSubject is set to null and only populated on existing feedback threads (FeedbackManager.java lines 227-245):

```
String userSubject = null;
String nameEmailSubject = PrefsUtil.getInstance().getNameEmailFromPrefs(context);
if (nameEmailSubject != null) {
    // Prepopulate the appropriate fields
    String[] nameEmailSubjectArray = nameEmailSubject.split("\\|");
    if (nameEmailSubjectArray != null && nameEmailSubjectArray.length >= 2) {
        userName = nameEmailSubjectArray[0];
        userEmail = nameEmailSubjectArray[1];
        if (!forceNewThread && nameEmailSubjectArray.length >= 3) {
            userSubject = nameEmailSubjectArray[2];
        }
    }
}
intent.putExtra(FeedbackActivity.EXTRA_INITIAL_USER_NAME, userName);
intent.putExtra(FeedbackActivity.EXTRA_INITIAL_USER_EMAIL, userEmail);
intent.putExtra(FeedbackActivity.EXTRA_INITIAL_USER_SUBJECT, userSubject);
intent.putExtra(FeedbackActivity.EXTRA_INITIAL_ATTACHMENTS, getInitialAttachments(attachments));
intent.putExtra(FeedbackActivity.EXTRA_USER_ID, FeedbackManager.userId);
return intent;
```

Please let me know if I can provide more information.

**Comment by jaelim-ms** [comment]
I understand that you want to set your own subject to users in FeedbackActivity but current HA doesn't support this functionality yet.
If you just need to set a default subject to the Activity, there is a workaround.
You should be able to write your own FeedbackActivity and FeedbackManagerListener, just returning your FeedbackActivity in overridden `getFeedbackActivityClass` method in your listener class.
Then pass your listener instance when you register FeedbackManager, it should unblock what you are trying to do.

**Comment by vandert** [comment]
OK.  Thanks for the response.
