### ISSUE TITLE
Resource leak identified by StrictMode

### ISSUE THREAD

**Issue by FabianFrank** [bitstadium/HockeySDK-Android#39]
04-16 17:26:18.443 16425-16434/com.relateiq.android E/StrictMode﹕ A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
java.lang.Throwable: Explicit termination method 'close' not called at dalvik.system.CloseGuard.open(CloseGuard.java:184) at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:278) at com.android.org.conscrypt.OpenSSLSocketImpl.getSession(OpenSSLSocketImpl.java:741) at org.apache.http.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:92) at org.apache.http.conn.ssl.SSLSocketFactory.createSocket(SSLSocketFactory.java:388) at org.apache.http.impl.conn.DefaultClientConnectionOperator.updateSecureConnection(DefaultClientConnectionOperator.java:231) at org.apache.http.impl.conn.AbstractPoolEntry.layerProtocol(AbstractPoolEntry.java:302) at org.apache.http.impl.conn.AbstractPooledConnAdapter.layerProtocol(AbstractPooledConnAdapter.java:146) at org.apache.http.impl.client.DefaultRequestDirector.establishRoute(DefaultRequestDirector.java:654) at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:370) at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:555) at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:487) at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:465) at net.hockeyapp.android.CrashManager.submitStackTraces(CrashManager.java:266) at net.hockeyapp.android.CrashManager$3.run(CrashManager.java:394)

It would be desirable to use java.net.HttpURLConnection anyways, since the apache client is deprecated since Android 2.3.

**Comment by ranterle** [comment]
Please have a look at our recent 3.6 beta 1 which dumps Apache HttpClient for HttpURLConnection: http://hockeyapp.net/blog/2015/09/04/hockeysdk-android-3-6-beta-1-release-notes.html
