### ISSUE TITLE
White buttons on 'report crash' alert

### ISSUE THREAD

**Issue by apcrompton** [bitstadium/HockeySDK-Android#394]
Hi there,

We have had reports of users not being able to report crashes on certain devices and Android versions because they cannot see any buttons on the alert. We have not been able to reproduce this issue but we are guessing this is because the buttons on the alert are white.

We are using the latest version of the Android Hockeyapp SDK as of writing (v5.1.0)

![screenshot_20180806-165450](https://user-images.githubusercontent.com/7825080/43930738-69c4c0ca-9c7e-11e8-840c-6329fac9384b.png)
Android 6.0 Nexus 5

![img 1](https://user-images.githubusercontent.com/7825080/43930759-912a6ffc-9c7e-11e8-9d2f-c07d40b90dc0.jpg)
Android 6.0.1 Samsung SM-J327P

If you could look into this issue, that would be much appreciated.

Thanks

Alex Crompton

**Comment by jwallra** [comment]
I wasn't able to reproduce the issue on the devices you listed.  Are you using the most recent version of the Hockey App SDK?  Are the devices using the default Android theming?  Did you observe these issues on a physical device or a virtual one?  If it was a physical device, are you able to reproduce on a virtual device?

**Comment by jwallra** [comment]
@apcrompton Let us know if you're still having problems with this.  I'm going to close it for now.

**Comment by apcrompton** [comment]
Hi @jwallra sorry about not getting back to you sooner, yes we are still having this issue. I have noticed that our `colorAccent` is actually white (which is correct in our app). Could this be causing this issue? Also, is there any way around this, given that we still would like to keep our white accent color?

This issue has been observed on physical devices (the screenshots are from user reports). We have not been able to reproduce the issue ourselves either in the emulator or on our physical devices (Samsung GS7 running Android 8.0, Nexus 6P running Android 7.1)

**Comment by jwallra** [comment]
You can provide your own crash dialog UI by implementing the [CrashManagerListener](https://github.com/bitstadium/HockeySDK-Android/blob/develop/hockeysdk/src/main/java/net/hockeyapp/android/CrashManagerListener.java), then passing your new listener to the `register` call when you register the Crashes SDK (see the implementation [here](https://github.com/bitstadium/HockeySDK-Android/blob/develop/hockeysdk/src/main/java/net/hockeyapp/android/CrashManager.java#L130).

Let me know if you have more questions :)
