### ISSUE TITLE
Update Manager Found New Update even when the installed version is the same as latest one

### ISSUE THREAD

**Issue by bahaa-ka** [bitstadium/HockeySDK-Android#400]
i have this problem 
i am using the in app update feature of hockeyapp sdk 
the problem as i mention , when the app (with version for example 2) check for update it prompt that there is a new version , but the new version is the same as the installed one (with the same version code and name) 
what the solution for this ?

**Comment by ElektrojungeMS** [comment]
Hey @bahaa-ka,

This doesn't sound right but we are not aware about any issues at this time. Can you please share the following information with us:

* which SDK version you are using?
* which Android version you are using?
* `versionName` and `versionCode` for both versions?
* the code that you use to setup HockeySDK-Android as well as information where you are doing this?

My best guess is that something with your app versioning is off.

Best,
Benjamin

PS: In case you are not comfortable with sharing this information publicly, please get in touch through [our support](https://support.hockeyapp.net) and include a link to this github issue.

**Comment by bahaa-ka** [comment]
SDK Version : 5.1.1
android version : kitkat and above
latest version on hockey app is : 3.0 (3) ,version installed on devices : 3.0 (3)
the implementation:
`public void CheckForUpdates() {
        UpdateManager.register(MainActivity.this, AppConstants.APP_ID, new UpdateManagerListener() {
            @Override
            public void onNoUpdateAvailable() {
                final AlertDialog.Builder builder = new AlertDialog.Builder(MainActivity.this);
                builder.setTitle("No Update Avilable")
                        .setIcon(R.drawable.ic_update_dialog)
                        .setMessage("You are using the latest version of the App")
                        .setPositiveButton("Ok", new DialogInterface.OnClickListener() {
                            @Override
                            public void onClick(DialogInterface dialog, int which) {
                                dialog.cancel();
                            }
                        });
                builder.show();
            }
        });
    }` 
i call this function when a itemin navigation menu clicked, i just override the onNoUpdateAvailable() and added a message shown to the user that there is no update available

**Comment by bahaa-ka** [comment]
is there any way to check the version code returned from server
so i can check manually if the current version is the same as the returned from the hockeyapp server and eliminate this case

**Comment by MatkovIvan** [comment]
Hi @bahaa-ka,
There is `onUpdateAvailable` callback in `UpdateManagerListener` where the data coming from the server is passed as parameter. You can log it or watch through the debugger.

**Comment by bahaa-ka** [comment]
problem solved 
Thank You Guys @MatkovIvan @ElektrojungeMS

**Comment by ElektrojungeMS** [comment]
I'm glad that you were able to resolve the issue @bahaa-ka. I'm curious, what was the issue that you were running into?

**Comment by bahaa-ka** [comment]
@ElektrojungeMS to be honest with you , i dont know how 
when i tried to apply what matkovlan said , i said let me test it again before i made some changes and that what happend , the problem has gone by itself XD
