### ISSUE TITLE
No callback gets invoked when the crash-dialog gets dismissed

### ISSUE THREAD

**Issue by jakobulbrich** [bitstadium/HockeySDK-Android#402]
The dialog shown by the `CrashManager` is cancelable but does not invoke any listeners when it gets canceled by the user like the `UpdateManager` does with the `onCancel()`.
This makes it impossible to start this manager on a splash-screen (the first screen in the app) and postpone the redirection to the other screen until the user has closed the dialog and/or sent the crashes.

**Comment by MatkovIvan** [comment]
Hi @jakobulbrich,

Thank you for reporting this, we'll recheck this case. Most likely it shouldn't be cancelable.
Currently, you can override the dialog behavior using [`CrashManagerListener.onHandleAlertView`](https://github.com/bitstadium/HockeySDK-Android/blob/develop/hockeysdk/src/main/java/net/hockeyapp/android/CrashManagerListener.java#L142-L149) as workaround. 

Thanks,
Ivan

**Comment by ElektrojungeMS** [comment]
Hey @jakobulbrich,

We're considering this a feature request and will track this in our backlog accordingly. That said, we're currently focussing on [App Center](appcenter.ms) and it's SDKs which are also open source on Github, so I cannot give you an ETA for the new API that you're requesting. App Center is the future for HockeyApp, so check out our [roadmap](https://hockeyapp.net/appcenter/about/). 
That said, we're happy to accept PRs for HockeySDK-Android. ;)

Cheers!
Ben
