### ISSUE TITLE
Not logging TransactionTooLargeException

### ISSUE THREAD

**Issue by aednlaxer** [bitstadium/HockeySDK-Android#406]
We've got `TransactionTooLargeException`s caused by passing large parcel objects via Intent but HockeyApp is not logging those crashes. Other crashes appear in the HockeyApp almost immediately after reopening the app (when crashes are being uploaded) so it's not a problem with the crash upload.

This is our setup:
```java
CrashManager.register(this, new CrashManagerListener() {
        @Override
        public boolean shouldAutoUploadCrashes() {
          return true;
        }
      });
```

Code causing an exception:
```java
bundle.putParcelable("content", largeObject);
```

Is it a known behaviour?

**Comment by ElektrojungeMS** [comment]
Hey Alexander,

thanks for getting in touch. We're not aware of this but will definitely look into it and keep you posted. What version of the HockeySDK are you using?
Who's sending and receiving the event?
I'd be great to have that info because it will help us reproduce and fix the issue.

Thanks for using HockeyApp!

**Comment by ElektrojungeMS** [comment]
Hey Alex,

I'm unable to reproduce the issue, please provide the info that I requested, especially the context of who's sending and receiving the intent.
If the crash in `bundle.putParcelable("content", largeObject);` is happening in a background service which does not integrate the HockeyApp SDK (which is not supported but some people do it anyway), the crash cannot be detected by the SDK.

**Comment by aednlaxer** [comment]
Hey Benjamin,

>What version of the HockeySDK are you using?

We're using HockeyApp SDK v5.1.0

>who's sending and receiving the intent 

Intent is created in a fragment. It supposed to launch an activity and pass an object to it. The object is huge and it throws a `TransactionTooLargeException` that is not logged to HockeyApp

**Comment by aednlaxer** [comment]
That's weird but other `TransactionTooLargeException`s thrown in a different place are logged in HockeyApp. Now I'm trying to understand the different between these exceptions

**Comment by ElektrojungeMS** [comment]
Hey @aednlaxer,
sorry for the wait. I cannot repro the issue you are seeing, I'm running into OOM exceptions before I get to see a `TransactionTooLargeException`. Can you share a code snippet that I can use to reproduce the issue?

**Comment by ElektrojungeMS** [comment]
Hey!
We haven't heard from you in a while so I'm closing this issue but please feel free to reopen and comment.

Best,
Benjamin
