### ISSUE TITLE
Able to spawn multiple download tasks (Suggestion)

### ISSUE THREAD

**Issue by Corical** [bitstadium/HockeySDK-Android#407]
I've implemented it on a fork (I have some extra tweaks) but it might be a good idea to implement. I disable the **button_update** in `UpdateFragment` at the start of `startDownloadTask()`, then enable it again in `downloadFailed()` and `OnPause()` override.

This is because on slower connections or when it takes a while to resolve host a user can tap it multiple times and it actually spawns multiple download tasks. Re-enable on `OnPause()` because if you come back after cancelling to install it should be re-enabled. Suppose it could have been in `OnResume()` as well.

Not sure what you would have preferred, to maintain the download task (do not allow if one is already in progress) or disabling the UI.

**Comment by clpolet** [comment]
Thanks for your feedback @Corical. I am trying to understand, do you mean that in some conditions users can tap the `button_update` multiple times and that's spawning multiple download tasks for the same release?

**Comment by Corical** [comment]
Hi, that's correct yes. Sorry I didn't include my version but I had a look at current code of UpdateFragment and it seems like it will suffer the same fate. 

So essentially right before the (download) progress bar pops up there's an opportunity to tap the download button multiple times after the first tap, that will result in multiple downloads.

**Comment by MatkovIvan** [comment]
Hi @Corical,

Since you've already implemented the fix, could you please to send it as PR? We would like to merge it after reviewing and testing.

**Comment by MatkovIvan** [comment]
Let's keep this issue open until the fix is merged

**Comment by clpolet** [comment]
I would prefer:
> do not allow if one is already in progress

The UI is customizable and can be fully replaced by devs, in this case they'll miss the fix.
