### ISSUE TITLE
Documentation Update

### ISSUE THREAD

**Issue by ewoks** [bitstadium/HockeySDK-Android#408]
[Readme.md](https://github.com/bitstadium/HockeySDK-Android/blob/develop/README.md) points to this link as [Getting Started Integration in Android App](https://support.hockeyapp.net/kb/client-integration-android/hockeyapp-for-android-sdk#setup).
However, it looks like that page is not maintained for some time (or it is automatically updated) so it describes legacy way of integrating dependencies, i.e.:
wrong: `compile 'net.hockeyapp.android:HockeySDK:5.1.1'`, instead of 
correct: `implementation 'net.hockeyapp.android:HockeySDK:5.1.1'`.

Linked page should be checked for more legacy instructions and corrected respectively

**Comment by ElektrojungeMS** [comment]
Hi @ewoks,

thanks for notifying us about this. I just updated the page to use the `implementation` keyword.

Best,
Benjamin
