### ISSUE TITLE
Incorrect AlertDialog import

### ISSUE THREAD

**Issue by SzyQ** [bitstadium/HockeySDK-Android#416]
Please change import in
https://github.com/bitstadium/HockeySDK-Android/blob/develop/hockeysdk/src/main/java/net/hockeyapp/android/UpdateFragment.java
from import android.app.AlertDialog; to support.
When using android X and material themes android.app.AlertDialog have incorrect style, so in this case
import androidx.appcompat.app.AlertDialog;
should be used.
Otherwise please allow to set custom theme, so that this issue is worked around

**Comment by dtrabo** [comment]
Hi @SzyQ! Sorry, but we won't fix this because it violates one of our core rules  – which is to not have any or as little outside dependency. You can override show dialog behavior, please take a look at this https://github.com/bitstadium/HockeySDK-Android/issues/329
