### ISSUE TITLE
UpdateManager.register - no callback method calls in oppo f11 

### ISSUE THREAD

**Issue by pradipvadher** [bitstadium/HockeySDK-Android#427]
Hello sir,

i have been implemented hockey app sdk in my android project for testing purpose. hockey app sdk version is 5.1.1.

i will check for update in welcome screen, but in oppo f11 device any of updatemanager.register method is not called. 

so i looks like welcome screen is freeze so tester not able to open app. 

issue i found that all three methods (**onNoUpdateAvailable(), onUpdateAvailable() and onUpdateAvailable(JSONArray data, String url)**)  are not callback when checking for update
and also there has no method for failure. so i can identify error

same issue found in oppo device lollipop 5.1.1 version

**Comment by AnastasiaKubova** [comment]
Hi, @pradipvadher ! Thank you for contacting us! Could you please clarify some moments:
- What the permissions do you use? Please, make sure that it matches these requires https://support.hockeyapp.net/kb/client-integration-android/hockeyapp-for-android-sdk#2-6-add-update-distribution and these https://support.hockeyapp.net/kb/client-integration-android/hockeyapp-for-android-sdk#4-7-permissions
- What the error you identified?
- Could you please send verbose logs?

**Comment by pradipvadher** [comment]
hi, @AnastasiaKubova 

Thank you for you support!

all permissions and implementation are correct and also working in more than 100 devices.

the issue was occur in oppo device only, my application are working fine in other device.

i can't find any error message and i am also not able to provide you logs because issue found in tester.

**Comment by AnastasiaKubova** [comment]
Hi! Unfortunately, we can’t help you without any logs or other information joining with your problem. Could you please reproduce this issue and provide us any information?

**Comment by MatkovIvan** [comment]
Hi @pradipvadher!

We haven't heard from you in a while and provided information isn't enough for the future investigation, so I'm closing this issue. Please reopen/comment if you have more details or have any other questions.

Thanks,
Ivan

**Comment by pradipvadher** [comment]
hi @AnastasiaKubova, 

Getting same issue in realme 1 device, but the problem is i am not able to provide you any logs, because this issue are faced in my tester's device.

Can you add any failure method or any timeout error so i can navigate to app?

My app's current scenario is, user is not go through app until check for hockey updates. but not getting response from register method.

**Comment by russelarms** [comment]
Hi @pradipvadher, we are not working on implementing any new features for HockeySDK, as the migration to [AppCenter](https://appcenter.ms) is underway. I would advise you to try it with AppCenter on the same devices, and if the problem persists, open a new issue.

**Comment by pradipvadher** [comment]
by migrating to appCenter, should i have to change my code or hockey SDK?

**Comment by dtrabo** [comment]
Hi @pradipvadher, please take a look at our transition docs and let me know if you have additional questions. https://docs.microsoft.com/en-us/appcenter/transition/
