### ISSUE TITLE
Misuse of AsyncTask

### ISSUE THREAD

**Issue by cuixiaoyiyi** [bitstadium/HockeySDK-Android#433]
According to our research, there are misuses about the following AsyncTask class:
( net.hockeyapp.android.PaintActivity )
```
//……
 @SuppressLint("StaticFieldLeak")
    private void makeResult() {
        //...
        AsyncTaskUtils.execute(new AsyncTask<Void, Object, Boolean>() {})
     }
 }
```

The problems are:
1. It is inner class. It holds strong reference to the GUI element of Activity( PaintActivity ), which can lead to memory leak when the Activity is destroyed and the AsyncTask did not finish.
2. Its instances are not cancelled before the Activity is destroyed, which can lead to the wrong invocation of onPostExecute.
3. Its instance should be cancelled before the Activity is destroyed. But in the doInBackground method there are for or while loops without the call of isCancelled() . These loops may not be able to terminate when the task is cancelled. This will cause waste of resources or even flashback.

I think we can make following changes to fix the misuse problems:
1. I think the GUI-related fields should be wrapped into WeakReference. Take 
`private final PaintActivity _context` as example, it can be changed to `private final WeakReference<PaintActivity> _context`.
2. Define AsyncTask instance as a field instead of a local. Invoke `cancel()` in the onDestroy() method of PaintActivity.
3. Every loop should check the status of AsyncTask to break the loop.
```
while(condition1){
     if(isCancelled()){
          break;
     }
     //blablabla…
     while(condition2){
         if(isCancelled()){
              break;
         }
         //blablabla…
     }
}
```

These are my suggestions above, thank you.

**Comment by hamswan** [comment]
Thanks for bringing this to our attention. We are looking into this, but since Hockeyapp is going to be shutdown in Nov, we would like you to consider moving to Appcenter. Please let us know if you need any help with transitioning.
