### ISSUE TITLE
Weak SSL Cipher Suites are Supported and Lack of Certificate Pinning

### ISSUE THREAD

**Issue by n00bm5st3r69** [bitstadium/HockeySDK-Android#434]
Our security team has performed a security scan on our mobile application and found the following vulnerabilities: 

**Vulnerability Name:** Weak SSL Cipher Suites are Supported
**Vulnerability Type:** attWeakCipherSuites
**Calling Method:** net.hockeyapp.android.utils.HttpURLConnectionBuilder.build():java.net.HttpURLConnection
**Method Signature:** javax.net.ssl.SSLParameters.setCipherSuites(java.lang.String[]):void
**Location:**  (net\hockeyapp\android\utils\HttpURLConnectionBuilder.java:156)
**Issue Validation Parameter -   Name:**  cipherSuites
**Issue Validation Parameter   - Value:**[TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,TLS_RSA_WITH_AES_128_GCM_SHA256,TLS_RSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_128_CBC_SHA,TLS_RSA_WITH_AES_256_CBC_SHA,TLS_EMPTY_RENEGOTIATION_INFO_SCSV]

-------------------------------------------------------------------------------------------------

**Vulnerability Name:** Lack of Certificate Pinning
**Vulnerability Type:** attSSLCertificatePinning 
**Calling Method:** net.hockeyapp.android.utils.HttpURLConnectionBuilder.build():java.net.HttpURLConnection
**Method Signature:** java.net.URL.openConnection():java.net.URLConnection
**Location:** (net\hockeyapp\android\utils\HttpURLConnectionBuilder.java:139)
**Issue Validation Parameter -   Name:**  this
**Issue Validation Parameter   - Value:** https://sdk.hockeyapp.net/api/2/apps/a839a0e297b24499aba816a9abe3710a/crashes/

Can someone help me resolve the issues above?

**Comment by MatkovIvan** [comment]
Hi @n00bm5st3r69,

I guess it can be treated as duplicate of #418

For the moment I would recommend you migrate to [AppCenter SDK](https://github.com/microsoft/appcenter-sdk-android) (see [the doc](https://docs.microsoft.com/en-us/appcenter/transition/) for details).
