### ISSUE TITLE
UpdateActivity AppTheme crash

### ISSUE THREAD

**Issue by swellner** [bitstadium/HockeySDK-Android#60]
In my App there is the latest HockeyApp SDK 3.0.2 implemented. My App is build with the Android 5.0 SDK and AppCompat Library from Google. I have set a apptheme (Theme.AppCompat.Light.DarkActionBar) in the styles.xml, to remove the shadow under ActionBar.

    <item name="android:windowContentOverlay">@null</item> 

With this style i get a crash without crash report or else if the UpdateActivity is shown (not the dialog). I cant see no more in the logcat except a Fatal Signal 11. I get this crash with the style parameter "android:windowContentOverlay" without it works perfectly.

I can reproduce this behaviour with the following setting:
Motorola Razr i
Android 4.2.1

On a Nexus 5 with Android 5 it doesnt crash.

http://support.hockeyapp.net/discussions/problems/31700-android-updateactivity-style

**Comment by duffinator** [comment]
Hi, no i think that happens only with devices with Android 4.2.1. We have only a Motorola Razr i with that Android version. It is not really a crash. It kills the application without a crash report dialog.
