### ISSUE TITLE
[Bug] Cannot properly localize FeedbackActivity 

### ISSUE THREAD

**Issue by markiyan-antonyuk** [bitstadium/HockeySDK-Android#64]
Strings in dialogs are hardcoded and cannot be localized through flow which is used to localize views and without change source code of the library.

**Comment by ashtom** [comment]
Do you use HockeySDK 3.5? If yes, which string is hardcoded?

**Comment by markiyan-antonyuk** [comment]
This is method in FeedbackActivity onDialogCreated, 413 line

**Comment by markiyan-antonyuk** [comment]
Found some more hardcoded strings which could not be localized in FeedbackActivity 491 and 498 line ("Select File" and "Select Picture").
Also there is hardcoded string which overwrites string from Strings.java in 659 line in FeedbackActivity.

**Comment by niedzielski** [comment]
Are there any localizations other than US English provided with the SDK?

**Comment by ashtom** [comment]
@niedzielski: The SDK 3.5 and 3.6 only comes with English.
