### ISSUE TITLE
Disable CrashManager

### ISSUE THREAD

**Issue by thaussma** [bitstadium/HockeySDK-Android#65]
We need to disable/enable the CrashManager while the App is running. I could not find how to do this.

**Comment by ashtom** [comment]
This is not directly possible, but you can call `Thread.setDefaultUncaughtExceptionHandler(null)` to unset the exception handler.

**Comment by thaussma** [comment]
Hmm ok. Are there any plans to implement such a feature? Would you accept pull requests?

**Comment by ashtom** [comment]
Sure, we are always happy about pull requests. To implement this correctly, you probably want to restore the previous handler, which is stored in our ExceptionHandler as defaultHandler.
