### ISSUE TITLE
Update Xamarin Binding to 3.5.0

### ISSUE THREAD

**Issue by tomquist** [bitstadium/HockeySDK-Android#66]
Since you didn't open-source the Xamarin-Binding for HockeySDK-Android I have to create an issue here. The Xamarin [HockeyApp-Android Component](https://components.xamarin.com/view/hockeyappandroid) is still at 3.0.2. Please update it to 3.5.0.

**Comment by ashtom** [comment]
The Xamarin bindings are not from us, but from Xamarin (the company) itself. We can't update those and have no access to the source. Please contact Xamarin.

**Comment by tomquist** [comment]
Oh, I'm sorry, I didn't know that. However, it would be a good idea to provide your own binding so it can be updated faster in future.
