### ISSUE TITLE
Add up button to Feedback Activity

### ISSUE THREAD

**Issue by perryao** [bitstadium/HockeySDK-Android#67]
Is there a way to add an Up button to the FeedbackActivity?

**Comment by ranterle** [comment]
I'm not sure I understand your whole question or the problem.
You can however always create your own feedback activity and return it via a custom [`FeedbackManagerListener`](https://github.com/bitstadium/HockeySDK-Android/blob/develop/src/main/java/net/hockeyapp/android/FeedbackManagerListener.java#L45)
