### ISSUE TITLE
Missing entry for "hockeyapp_crash_dialog_neutral_button" localization key

### ISSUE THREAD

**Issue by DenninDalke** [bitstadium/HockeySDK-Android#76]
Hi guys! Am I missed something, or the key "hockeyapp_crash_dialog_neutral_button" is missing in [LocaleManager.java](https://github.com/bitstadium/HockeySDK-Android/blob/3.5.0/src/main/java/net/hockeyapp/android/LocaleManager.java)?

I had to assign the key manually loading from resources then using Strings.set:

```java
int resId = context.getResources().getIdentifier("hockeyapp_crash_dialog_neutral_button", "string", context.getPackageName());
String string = context.getString(resId);
if (!TextUtils.isEmpty(string)) {
    Strings.set(resourceId, string);
}
```

**Comment by ashtom** [comment]
This was fixed with this commit the develop branch:
https://github.com/bitstadium/HockeySDK-Android/commit/348d481b32bc97a40df3d05443967bddd3055993
