### ISSUE TITLE
FeedbackManager: can't find referenced method setLatestEventInfo

### ISSUE THREAD

**Issue by the4thfloor** [bitstadium/HockeySDK-Android#79]
With Android M / 6 the method `public void setLatestEventInfo(Context context, CharSequence contentTitle, CharSequence contentText, PendingIntent contentIntent)` in `android.app.Notification` is gone.

This means that the HockeySDK can't be used with Android M / 6

```
Warning: net.hockeyapp.android.FeedbackManager: can't find referenced method 'void setLatestEventInfo(android.content.Context,java.lang.CharSequence,java.lang.CharSequence,android.app.PendingIntent)' in library class android.app.Notification
Warning: net.hockeyapp.android.tasks.ParseFeedbackTask: can't find referenced method 'void setLatestEventInfo(android.content.Context,java.lang.CharSequence,java.lang.CharSequence,android.app.PendingIntent)' in library class android.app.Notification
```

**Comment by ranterle** [comment]
Thanks, we're working on this. Of course, you're always welcome to file a PR ;-)

**Comment by ranterle** [comment]
Please take a look on our 3.6 Beta 1 which should contain the fixes proposed: http://hockeyapp.net/blog/2015/09/04/hockeysdk-android-3-6-beta-1-release-notes.html

**Comment by yekretsam** [comment]
I had the same issue, 3.6 beta 1 fixed it for me, thanks.

**Comment by ranterle** [comment]
Thanks for the info @yekretsam - I think we can close this now.
