### ISSUE TITLE
always_send_crash_reports should be part of published API

### ISSUE THREAD

**Issue by niedzielski** [bitstadium/HockeySDK-Android#92]
always_send_crash_reports is a preference key stored in the application's default SharedPreferences. The preference is used to determine whether crashes should be autouploaded. I propose that this should be part of the published API:
- The key is not terribly unique and, since the key is stored in the default preferences, may collide with a client key.
- It's a useful preference to expose in a developer settings UI.
- There's no other published mechanism for reading this state.

**Comment by ranterle** [comment]
Do I understand correctly, you want like a method on CrashManager to set the auto-send-feature value?
This is what the custom CrashManagerListener is for, with that you can override the behavior.
So we already have a public API for that.

Regarding the internal workings:
Even for a simple boolean, how we store the user selection on Auto-send is private API - it might be preference keys now, it might be something else entirely in the future. We could prefix the key's name with "hockeyapp_" in a future release to make it more unique and not clash with other keys from apps - but we have not heard of this issue before.

**Comment by niedzielski** [comment]
@ranterle, the use case is to allow the user to change their minds about sending crash reports. For example, we really, really want users to send us their crashes, so by default we have "always send" enabled. The user never sees a prompt unless they go to their settings where they can disable it.

What's the API to achieve this behavior? AFAIK, there's no API to show or set the current state so we'd have to keep a duplicate SharedPreference in sync with the SDK SharedPreference. We'd always return our copy of the SharedPreference in CrashManagerListener.shouldAutoUploadCrashes() but have to call CrashManager.resetAlwaysSend() whenever our copy was cleared by the user (see #93). Duplicating state causes bugs but the real problem is the UI. How could the client listen for when the user clicked "always send"? There's no CrashManagerListener.onUserConfirmedAlwaysSendCrashes().

I respect hiding the implementation but I don't think there's currently a good way to achieve this use case using the public API. The use case, of course, I would argue is a reasonable one :)

**Comment by ranterle** [comment]
I understand your argument with state duplication. I'll be looking into this.

**Comment by ranterle** [comment]
Added this to our backlog.

**Comment by niedzielski** [comment]
Is there a place I can track this now that it's been moved?

**Comment by ranterle** [comment]
@niedzielski unfortunately not, sorry. We are considering this for the next major version of the SDK.
