### ISSUE TITLE
Add CrashManagerListener.onCrash()

### ISSUE THREAD

**Issue by niedzielski** [bitstadium/HockeySDK-Android#94]
The SDK will not send a crash report until the application is relaunched. Since users may never launch the app again, this gives false crash numbers. Supplying an onCrash() callback will allow the app to restart the application which will send the report. We've a somewhat hacky implementation up here[0] for reference where HockeyAppCrashListener[0] is just a CrashManagerListener with the onCrash() method and HockeyAppExceptionHandler is an ExceptionHandler that calls it when available. An alternative to the callback would be to enable application restart or instant send functionality in the SDK.

[0] https://gerrit.wikimedia.org/r/#/c/237874/7/app/src/main/java/org/wikipedia/crash/hockeyapp/HockeyAppExceptionHandler.java
[1] https://gerrit.wikimedia.org/r/#/c/237874/7/app/src/main/java/org/wikipedia/crash/hockeyapp/HockeyAppCrashListener.java

**Comment by ranterle** [comment]
Thanks for the suggestion and the code sample. We are looking into possibilities of getting more direct crash reports, while still holding on to our privacy guidelines.

**Comment by ajhuntsman** [comment]
I think section 4.2.1 addresses this, in 3.7.0:

https://github.com/bitstadium/HockeySDK-Android

**Comment by ranterle** [comment]
@ajhuntsman there's a difference: Enabling automatic sending of crash reports only enables HockeySDK to send them without user interaction e.g. without asking them. Currently users will still have to relaunch the application - only then are crash reports sent (with or without user interaction).

What @niedzielski is suggesting instead and what we are working on is sending the crash reports in the moment the crash/uncaught exception occurs, right from the `ExceptionHandler`. There are both technical as well as privacy questions to sort out, but we're working on it to get it right.

**Comment by niedzielski** [comment]
@ranterle, I'm not seeing this in master. Has this been implemented?

**Comment by ranterle** [comment]
@niedzielski This is currently being discussed for a major next version of the SDK.
