### ISSUE TITLE
Android M removes method Notification.setLatestEventInfo

### ISSUE THREAD

**Issue by imort** [bitstadium/HockeySDK-Android#95]
When compiling against API 23. It should use NotificationBuilder as suggested [here](http://developer.android.com/preview/behavior-changes.html#behavior-notifications).

Warning: net.hockeyapp.android.FeedbackManager: can't find referenced method 'void setLatestEventInfo(android.content.Context,java.lang.CharSequence,java.lang.CharSequence,android.app.PendingIntent)' in library class android.app.Notification
Warning: net.hockeyapp.android.tasks.ParseFeedbackTask: can't find referenced method 'void setLatestEventInfo(android.content.Context,java.lang.CharSequence,java.lang.CharSequence,android.app.PendingIntent)' in library class android.app.Notification

Sorry didn't not find #79 first. Should be closed

**Comment by ranterle** [comment]
Hi @imort,
should have been resolved by #82. That will be in our 3.6 release soon. You can already test a [beta](http://hockeyapp.net/blog/2015/09/04/hockeysdk-android-3-6-beta-1-release-notes.html) and release candidate soon.
