### ISSUE TITLE
Can't save a picture attachment 

### ISSUE THREAD

**Issue by sgundumonu** [bitstadium/HockeySDK-Android#96]
I am testing Hockey App on Moto X running 5.1.
Upon attaching picture to user feedback form there is no option to save.
On Samsung S3 which has physical back, home and menu buttons, save option comes upon clicking physical menu button.
Without save option on no hard physical menu button phone, this feature will have very limited use.
Please fix this.

Thanks,
Sai

**Comment by ashtom** [comment]
If your app has no action bar, then you need to provide your own UI to save the attachment (or show the action bar when the feedback view becomes visible).
