### ISSUE TITLE
InstalledFromMarket always returns true

### ISSUE THREAD

**Issue by ubeyou** [bitstadium/HockeySDK-Android#99]
whenever we use Xiaomi, the installedFromMarket always return true.

Because when we debug via usb, it will display installer = "adb"

when we install via browser, it will shows installer = "com.android.browser"

Based on the written code, the result will always returned true whenever it's not empty.
result = !TextUtils.isEmpty(installer);

**Comment by ranterle** [comment]
Thanks for the mention, I'll be looking into this. For future reference I'll update the issue title to match the described issue.

**Comment by ranterle** [comment]
It seems that Xiaomi might me the issue of false behavior here. On all other devices `installerPackageName` will return `null` if the app was installed trough adb.

**Comment by ubeyou** [comment]
Perhaps u should create a whitelist for Xiaomi as it is pretty much owning 30% of SEA region devices.
